### ISSUE TITLE
建议： 所有库改为.Net Standard，应用迁移到.Net Core

### ISSUE THREAD

**Issue by mahoshojoHCG** [hanmin0822/MisakaTranslator#10]
[.Net Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) 可以方便类库在多个平台之间进行复用，而.Net Core的性能比.Net Framework更好，也更加现代。

**Comment by hanmin0822** [comment]
目前正在紧张准备2.0正式版的发布，以后如有时间会进行优化和修改!

**Comment by HumphreyDotSln** [comment]
类库是用.Net Standard写，但是由于部分上游库对.Net Core的支持不完整，暂时不考虑迁移到.Net Core

**Comment by AndromedaMelody** [comment]
Fix in 736cb4e794715a4cca59f882f78dd9f316d1611b
