### ISSUE TITLE
无法正常使用彩云小译

### ISSUE THREAD

**Issue by Hidoikoto** [hanmin0822/MisakaTranslator#104]
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/10/31 14:53
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.7.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionSource:TranslatorLibrary
ExceptionMessage:未将对象引用设置到对象的实例。
ExceptionStackTrace:   在 TranslatorLibrary.CaiyunTranslator.Translate(String sourceText, String desLang, String srcLang)
   在 MisakaTranslator_WPF.TranslateWindow.<>c__DisplayClass28_0.<DataRecvEventHandler>b__0()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by wangbich** [comment]
我也遇到了一样的情况

**Comment by SEAYuch** [comment]
同样

**Comment by imba-tjd** [comment]
See https://github.com/hanmin0822/MisakaTranslator/issues/131#issuecomment-868899350
