### ISSUE TITLE
在设置重复过滤阈值的时候输入空字符串会抛出错误并崩溃

### ISSUE THREAD

**Issue by NeneAyachi** [hanmin0822/MisakaTranslator#107]
在设置重复过滤阈值的时候输入空字符串会抛出错误并崩溃

错误信息
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/12/1 23:40
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.7.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionSource:mscorlib
ExceptionMessage:输入字符串的格式不正确。
ExceptionStackTrace:   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   在 MisakaTranslator_WPF.Common.RepairFuncInit()
   在 MisakaTranslator_WPF.GuidePages.Hook.ChooseTextRepairFuncPage.SentenceConfirm_Click(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()

**Comment by hanmin0822** [comment]
已知很久的bug了，但是现在无人维护

**Comment by sy1412** [comment]
> 
> 
> 已知很久的bug了，但是现在无人维护

想问一下 这个地方要输入什么才不会崩溃 还是说目前怎样都不行

**Comment by hanmin0822** [comment]
> > 已知很久的bug了，但是现在无人维护
> 
> 想问一下 这个地方要输入什么才不会崩溃 还是说目前怎样都不行

句子重复一般输入3或4，单字重复一个字重复几次就输入几，如果填写不行说明是系统问题，就自己手动修改配置文件

**Comment by sy1412** [comment]
> 
> 句子重复一般输入3或4，单字重复一个字重复几次就输入几，如果填写不行说明是系统问题，就自己手动修改配置文件
看来是这样 这种明显重复的 输入3或4会提示 句子去重出错
【日はとっくに暮れてしまったが、<br>表通りには派手な色のネオンサインが溢れている。冾ﾍとっくに暮れてしまったが、<br>表通りには派手な色のネオンサインが溢れている。はとっくに暮れてしまったが、<br>表通りには派手な色のネオンサインが溢れている。ﾍとっくに暮れてしまったが、<br>表通りには派手な色のネオンサインが溢れている。とっくに暮れてしまったが、<br>表通りには派手な色のネオンサインが。。。后面还有很多

**Comment by NeneAyachi** [comment]
> 已知很久的bug了，但是现在无人维护

不光是这个地方，用了几天发现好多地方非法输入都会引发异常然后崩溃，希望能改进一下。
另外这个句子去重问题我也是不管填多少都是去重错误，最后自己写的自定义

**Comment by HumphreyDotSln** [comment]
> > > 已知很久的bug了，但是现在无人维护
> 
> > 
> 
> > 想问一下 这个地方要输入什么才不会崩溃 还是说目前怎样都不行
> 
> 
> 
> 句子重复一般输入3或4，单字重复一个字重复几次就输入几，如果填写不行说明是系统问题，就自己手动修改配置文件

这个问题好久了..我依稀记得是输入之后会多出一个空格，但是大家都没有发现，做个输入格式化就好了

**Comment by imba-tjd** [comment]
should be fixed in 2022649b99ee7dae0c290b024410cc6b26d8ca50
