### ISSUE TITLE
= =为啥我用不了

### ISSUE THREAD

**Issue by zxsdSaMa** [hanmin0822/MisakaTranslator#11]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Exception: SQL logic error
no such table: gamelist
   在 MisakaTranslator.SQLiteHelper.ExecuteReader_OneLine(String sql, Int32 columns)
   在 MisakaTranslator.Common.GetGameID(String gamepath)
   在 MisakaTranslator.ProcessSelectForm.ConfirmBtn_BtnClick(Object sender, EventArgs e)
   在 HZH_Controls.Controls.UCBtnExt.lbl_MouseDown(Object sender, MouseEventArgs e)
   在 System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Label.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4150.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MisakaTranslator
    程序集版本:1.6.0.0
    Win32 版本:1.6.0.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/MisakaTranslator_x64.exe
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4001.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Config.Net
    程序集版本:4.0.0.0
    Win32 版本:4.14.23.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/Config.Net.DLL
----------------------------------------
netstandard
    程序集版本:2.0.0.0
    Win32 版本:4.8.3752.0
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4150.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MaterialSkin
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/MaterialSkin.DLL
----------------------------------------
Castle.Core
    程序集版本:4.0.0.0
    Win32 版本:4.4.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/Castle.Core.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4121.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DynamicProxyGenAssembly2
    程序集版本:0.0.0.0
    Win32 版本:4.4.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/Castle.Core.dll
----------------------------------------
DynamicProxyGenAssembly2
    程序集版本:0.0.0.0
    Win32 版本:4.4.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/Castle.Core.dll
----------------------------------------
HZH_Controls
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/HZH_Controls.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Data.SQLite
    程序集版本:1.0.112.0
    Win32 版本:1.0.112.0
    基本代码:file:///F:/Games/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/MisakaTranslator%E6%AD%A3%E5%BC%8F%E7%89%88V1.6/Misaka/System.Data.SQLite.DLL
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.4121.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.3752.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by hanmin0822** [comment]
这是1.6版本的固有bug，请使用2.0beta最新版，在群文件获取。
