### ISSUE TITLE
翻译窗口拖拽

### ISSUE THREAD

**Issue by ultrapre** [hanmin0822/MisakaTranslator#110]
目前仅红圈图标可以拖拽窗口。建议其他区域启用鼠标左键拖拽。
![image](https://user-images.githubusercontent.com/32613953/104445530-2c530c80-55d4-11eb-9fc5-3d8f82d9d11d.png)

**Comment by ultrapre** [comment]
还有，建议GUI添加夜间模式。

**Comment by HumphreyDotSln** [comment]
不认为有修改的必要。
