### ISSUE TITLE
可以考虑添加IBM的翻译API吗

### ISSUE THREAD

**Issue by littledgg** [hanmin0822/MisakaTranslator#122]
感觉效果会好一些，还没和deepl的对比过，每个月100w个字符

**Comment by imba-tjd** [comment]
https://cloud.ibm.com/docs/language-translator?topic=language-translator-translation-models#japanese

没有ja-zh的model，只能与en互转。如果还是有人真的有这个需求再留言。

**Comment by imba-tjd** [comment]
其实三天前我评论上面那句话的时候我已经做完了……，调试时才发现没有ja-zh的。但是做个先转en再转zh的也不难，就多几行代码就行。效果可能不好，不过国外的翻译基本上都是这样。
又但是我不会用Newtonsoft.Json，试了一下失败了。现在的内容在`ibm`分支里，迁移了一半，要把`System.Text.Json;`换掉（或者不换，就再加个依赖）。

**Comment by littledgg** [comment]
我心血来潮提了一下，你就试试了，我有点不好意思了，哈哈。唉，目前学的太少，不能搭把手，谢谢你的重视！
后续我会尽量发现并提出更有建设性的意见的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 下午4:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hanmin0822/MisakaTranslator] 可以考虑添加IBM的翻译API吗 (#122)





 
其实三天前我评论上面那句话的时候我已经做完了……，调试时才发现没有ja-zh的。但是做个先转en再转zh的也不难，就多几行代码就行。效果可能不好，不过国外的翻译基本上都是这样。
 又但是我不会用Newtonsoft.Json，试了一下失败了。现在的内容在ibm分支里，迁移了一半，要把System.Text.Json;换掉（或者不换，就再加个依赖）。

**Comment by imba-tjd** [comment]
现在ibm分支的应该可以用了，想用的下[artifact](https://github.com/hanmin0822/MisakaTranslator/actions/runs/922295334)。

往settings.ini中手动添加以下两项容易找到的参数：

```
[IBMTranslator]
IBMApiKey=xxx
IBMURL=xxx
```

然后设置里选IBM翻译就可以用了。可以先用翻译剪切板内容测试。

我用起来，可能出现只能翻译半句的问题。日语翻到英语时，句号会连起来，再翻到中文就会出问题。
网速尚可，没有出现超时的问题。
最大的优点是是国外的，不用担心查水表。
注册送一百万字符免费额度，无需信用卡。不过要先翻译到英文，实际要大打折扣。

我不会xaml，设置界面没有单独的tab来设置参数。本来我打算先留在ibm分支里不合并到master的，等有设置了再合并。不过现在决定还是直接合并了。改ini也不难。
