### ISSUE TITLE
同是http://translate.google.cn 翻译结果不一样

### ISSUE THREAD

**Issue by cool-delete** [hanmin0822/MisakaTranslator#125]
**关于哪一项功能**

@imba-tjd 
设置的Google公用接口
**期望的效果**
与网页端能一致
<summary>历史记录<details>
始始「「吐吐いいててーー」」
始： “”“”“”“

==================================
理穂理穂「「んん…………すすぅぅぅぅ…………」」
Ryumao“”非..........................“”

==================================
始始「「ははいい吸吸っっててーー」」
开始“”我有一个很好的吸吮

==================================
始始「「深深呼呼吸吸ししろろ、、深深呼呼吸吸だだっっ！！」」
</details></summary>

使用沙拉查词的划词翻译 也是公共接口啊 但是好很多
![image](https://user-images.githubusercontent.com/13638610/120259512-ae637980-c2c6-11eb-9e8c-8465678d0263.png)
![image](https://user-images.githubusercontent.com/13638610/120880678-4b435100-c5fe-11eb-9a41-ce6b0c50df48.png)
![image](https://user-images.githubusercontent.com/13638610/120881040-e2a9a380-c600-11eb-8628-5ee2d3a8f5d4.png)

**Comment by cool-delete** [comment]
没看错吧 
https://github.com/hanmin0822/MisakaTranslator/blob/4294b37eb985ba93a3fd5fd090c56124fa33e351/TranslatorLibrary/GoogleCNTranslator.cs#L44

**Comment by imba-tjd** [comment]
我不知道该怎么做。

**Comment by cool-delete** [comment]
> 现在你提供的“详细记录”里的有重复，我不知道它仅仅是记录的是重复的但是实际发送的内容去了重，还是你就是没去重。我也不知道“详细记录”里的文字用沙拉查词的翻译结果是什么。不过确实和网页版翻译的结果不一样。接口里那么多参数，我也不知道有什么作用。

捕获的方法处理前是每个字都变成两个字的 所以我去重了2个字 变成了单字 
日文如下
```
今日も『ホームズ』は、迷える学園生の来訪を密かに待っている―。
今天，“福尔摩斯”偷偷地等待了可以丢失的拜访学生 - 。

==================================
曰く、その部屋を訪れば、女子に起こる特殊なトラブルを解決してもらえる。
好吧，参观房间以解决女孩的特殊麻烦。

==================================
曰く、誰も近寄らない古い部室棟の端っこに、『ホームズ』と呼ばれる部屋がある。
好吧，有一个房间在旧俱乐部建筑的尽头，没有人接近的房间。

==================================
七不思議とかの類ではなく、人助けにかわる話だ。
它不是七种菜肴的类别，而是一个帮助人们帮助的故事。

==================================
```

不处理的话 方法捕获是这样的

`七七不不思思議議ととかかのの類類ででははななくく、、人人助助けけににかかかかわわるる話話だだ。。`


![image](https://user-images.githubusercontent.com/13638610/120894052-0c86b880-c649-11eb-8f0a-ceb679d6932a.png)

js 我还好 其实路径虽然我没试过 但是加了参数其实只是决定了返回的格式吧 
因为我不会c#
https://github.com/hanmin0822/MisakaTranslator/blob/4294b37eb985ba93a3fd5fd090c56124fa33e351/TranslatorLibrary/GoogleCNTranslator.cs#L44
所以这条语句源文本是什么
我去试试

**Comment by imba-tjd** [comment]
好像是比网页版的差很多。我这里测试用client=gtx的api是和网页版一致的。

```py
import requests
from urllib.parse import quote

API = 'https://translate.google.cn/translate_a/single?client=gtx&sl={}&tl={}&dt=t&q='
s = requests.session()

def translate(text, sl='zh-CN', tl='en')->str:
    r = s.get(API.format(sl,tl)+quote(text))
    return r.text

texts = [
    '今日も『ホームズ』は、迷える学園生の来訪を密かに待っている―。',
    '曰く、その部屋を訪れば、女子に起こる特殊なトラブルを解決してもらえる。',
    '曰く、誰も近寄らない古い部室棟の端っこに、『ホームズ』と呼ばれる部屋がある。',
    '七不思議とかの類ではなく、人助けにかわる話だ。'
]

results=[]

for text in texts:
    results.append(translate(text,'ja','zh-CN'))

with open('result.json', 'w+',encoding='u8') as f:
    f.write(str(results))
```

既然webapp的效果这么差，gfx看起来又和网页版一样，那可以考虑改一改。不过在`https://github.com/lmk123/crx-selection-translate/issues/223`里有人说client=at的效果比gfx好，另外在`https://hcfy.limingkai.cn/docs/faq/#why-result-different`表示有的API有次数限制，感觉有点麻烦。

---

现在用的client=webapp，tk参数要根据输入的内容计算出来，在上面一句`var tk = ExecuteScript(fun, GetTkkJS);`里。ExecuteScript是用来执行JS函数的，JS函数的内容在GetTkkJS里，在TranslatorInit读进来，实际内容如下：

```js
function TL(a) { 
        var k = ""; 
        var b = 406644; 
        var b1 = 3293161072; 
        var jd = "."; 
        var $b = "+-a^+6"; 
        var Zb = "+-3^+b+-f"; 
        for (var e = [], f = 0, g = 0; g < a.length; g++) { 
            var m = a.charCodeAt(g); 
            128 > m ? e[f++] = m : (2048 > m ? e[f++] = m >> 6 | 192 : (55296 == (m & 64512) && g + 1 < a.length && 56320 == (a.charCodeAt(g + 1) & 64512) ? (m = 65536 + ((m & 1023) << 10) + (a.charCodeAt(++g) & 1023), 
            e[f++] = m >> 18 | 240, 
            e[f++] = m >> 12 & 63 | 128) : e[f++] = m >> 12 | 224, 
            e[f++] = m >> 6 & 63 | 128), 
            e[f++] = m & 63 | 128) 
        } 
        a = b; 
        for (f = 0; f < e.length; f++) a += e[f], 
        a = RL(a, $b); 
        a = RL(a, Zb); 
        a ^= b1 || 0; 
        0 > a && (a = (a & 2147483647) + 2147483648); 
        a %= 1E6; 
        return a.toString() + jd + (a ^ b) 
    }; 
    function RL(a, b) { 
        var t = "a"; 
        var Yb = "+"; 
        for (var c = 0; c < b.length - 2; c += 3) { 
            var d = b.charAt(c + 2), 
            d = d >= t ? d.charCodeAt(0) - 87 : Number(d), 
            d = b.charAt(c + 1) == Yb ? a >>> d: a << d; 
            a = b.charAt(c) == Yb ? a + d & 4294967295 : a ^ d 
        } 
        return a 
    }
```

怎么来的我不知道，反正不可维护。

**Comment by cool-delete** [comment]
https://github.com/frederick-wang/translate-many-times/blob/4ed0b349d3b44ca151650fcd3e5a5253ef3d9b18/index.js#L74
这里提到client=gtx的限制 不是过多吧  我魔改了一个translate-many-times 可是我忘了做延时 ip在93次的时候被封了 解封好像需要30天 
加了5秒的延时了 
已上传到https://github.com/cool-delete/translate-many-times了 
你只要有node环境 可以跑一下看看

**Comment by imba-tjd** [comment]
现在可以确定的是用了gtx，测试的这几条翻译结果和网页版一样。
要不要保留tk参数呢？可以确定gtx不加tk也能用，但加了会不会更好？比如能用的额度更高。如果加，它的生成方式是与client=webapp一样还是不一样？
超额以后其它人遇到的好像是403和5xx，和你的不一样。不清楚多久解封。
不过公共接口本来就是用于测试的，大量使用还是用有认证的接口。基于这一点，就直接改成用gtx并且去掉tk参数？超额不做任何处理？

**Comment by cool-delete** [comment]
认证的接口我也试了 可是翻译质量真的惨不忍睹 很多句子直接给我返回"......." 不知道是被和谐了还是怎么样 没法控制变量
所以才试了网页端的 
***
ip不能重置好蛋疼 用了手机热点 我用每条5秒 每10条60秒来测试 跑到160没问题 等下在跑5000次试试
***
顺便问一下 我看releases是大半年前了 没有pre-build吗 新版不会要加群拿吧 难道要我自己build啊

**Comment by imba-tjd** [comment]
一般用彩云的吧。
build现在可以用Actions里的artifacts，但是lib文件夹要自己手动复制一下。
现在和网页版结果一样了。

![图片](https://user-images.githubusercontent.com/24759802/120912684-d89ca900-c6c3-11eb-9ef7-1d03108b1861.png)

**Comment by cool-delete** [comment]
....我彩云还没通过 用的测试版token 但是跟你的结果不一样欸??
```==================================
曰く、その部屋を訪れば、女子に起こる特殊なトラブルを解決してもらえる。
他说，如果你去那个房间，你可以帮助解决女生遇到的特殊麻烦。

==================================
曰く、誰も近寄らない古い部室棟の端っこに、『ホームズ』と呼ばれる部屋がある。
他说，在一个没有人敢靠近的老房间的尽头，有一个叫福尔摩斯的房间。

==================================
七不思議とかの類ではなく、人助けにかわる話だ。
这不是什么七大不可思议，而是帮助别人的故事。

==================================
今日も『ホームズ』は、迷える学園生の来訪を密かに待っている―。
今天，“福尔摩斯”偷偷地等待可以丢失的拜访学生 - 。
```

***
我有点想新开issue了 artifacts里面的debug版加入不了游戏啊
你说lib手动复制 我把***Library这些文件夹都拖进去报错了
```
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2021/6/6 14:00
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.7.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionName:System.NullReferenceException
ExceptionSource:TextHookLibrary
ExceptionMessage:未将对象引用设置到对象的实例。
ExceptionStackTrace:   在 TextHookLibrary.TextHookHandle.<AttachProcess>d__30.MoveNext() 位置 D:\a\MisakaTranslator\MisakaTranslator\TextHookLibrary\TextHookHandle.cs:行号 175
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 TextHookLibrary.TextHookHandle.<StartHook>d__35.MoveNext() 位置 D:\a\MisakaTranslator\MisakaTranslator\TextHookLibrary\TextHookHandle.cs:行号 243
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by imba-tjd** [comment]
我上面的截图是谷歌的。至于TextHookLibrary的报错嘛，我只能说我没问题。

**Comment by cool-delete** [comment]
...看不懂`位置 D:\a\MisakaTranslator\MisakaTranslator\TextHookLibrary\TextHookHandle.cs`
我也没这路径啊?

**Comment by imba-tjd** [comment]
那是CI构建时的路径吧

**Comment by cool-delete** [comment]
可能我姿势不对吗?
去action里面 下载artifacts
这个zip解压 打开里面的MisakaTranslator-WPF.exe
除了这些还要做什么

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/120915844-9762c400-c6d8-11eb-8ddd-fde7d058c4f1.png)

**Comment by cool-delete** [comment]
....
![image](https://user-images.githubusercontent.com/13638610/120915899-f9bbc480-c6d8-11eb-9b16-e425da27ef45.png)
解压包没有这个文件...

**Comment by imba-tjd** [comment]
所以我要你手动复制一下啊，从release了的2.7里复制

**Comment by cool-delete** [comment]
哦哦... 行了 谢谢大佬 可以关闭close了

**Comment by imba-tjd** [comment]
我试用了一下，额度非常少，只能坚持几分钟。超额后也是429 Too Many Requests。你说“解封好像需要30天”是怎么知道的？

**Comment by cool-delete** [comment]
直接搜的...忘了在哪了 后续发现不用30天 半天之后又能给你十几次访问次数 而且我直接在翻译器里面使用没问题

**Comment by cool-delete** [comment]
额 记起来了 封了ip后我试着用网页访问那个网址  然后看respond的参数 写着一串数字 然后搜一下那串数字 就发现有人说需要30天
