### ISSUE TITLE
游戏中翻译时，索引超出了数组界限

### ISSUE THREAD

**Issue by sannmizu** [hanmin0822/MisakaTranslator#129]
**关于哪一项功能**
游戏对话翻译崩溃

**问题描述**

翻译只配置了百度翻译，玩的游戏是【継承される勇者のRPG_モザイク】。
能检测到npc的对话文本，此时翻译正常，但是检测到的主角的文本前面有部分乱码，此时翻译就会报错。
检测到的npc和旁白的文本格式如下：
![Quicker_20210618_135022](https://user-images.githubusercontent.com/53028899/122513078-7a18e880-d03c-11eb-8b9e-713b92f4ad4b.png)
 检测到的主角的文本格式如下：
![Quicker_20210618_135054](https://user-images.githubusercontent.com/53028899/122513104-8604aa80-d03c-11eb-871f-2b0ca3e3e95b.png)

**应用版本**
2.7

**系统信息**
Windows10 x64 专业版

**错误信息**
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2021/6/18 12:44
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.7.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionSource:MeCab.DotNet
ExceptionMessage:索引超出了数组界限。
ExceptionStackTrace:   在 MeCab.Core.Tokenizer.Lookup(Char* begin, Char* end)
   在 MeCab.Core.Viterbi.DoViterbi(Char* sentence, Int32 len, ThreadData work)
   在 MeCab.Core.Viterbi.Analyze(Char* str, Int32 len)
   在 MeCab.MeCabTagger.ParseToNode(String str)
   在 MeCab.MeCabTagger.<ParseToNodes>d__25.MoveNext()
   在 MecabHelperLibrary.MecabHelper.SentenceHandle(String sentence)
   在 MisakaTranslator_WPF.TranslateWindow.<>c__DisplayClass28_0.<DataRecvEventHandler>b__0()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 MisakaTranslator_WPF.App.Main()

**Comment by imba-tjd** [comment]
别开显示原文
