### ISSUE TITLE
可以隐藏菜单栏吗

### ISSUE THREAD

**Issue by darkness151103** [hanmin0822/MisakaTranslator#133]
全屏翻译时，翻译界面上方一排的菜单栏有些突兀，希望能够隐藏

**Comment by login404** [comment]
配合Magpie刚需
虽然好像弃坑了…

**Comment by luojunyuan** [comment]
> 配合Magpie刚需 虽然好像弃坑了…

Magpie 把游戏窗口映射到显示器分辨率的大小，此时鼠标最大活动的范围实际上是仍然维持在原本窗口大小的范围。操作游戏以外的窗口挺麻烦的想不到有什么好的方式。你如果有俩显示器你可以尝试把Misika拖动到副显示器使用

**Comment by login404** [comment]
> > 配合Magpie刚需 虽然好像弃坑了…
> 
> Magpie 把游戏窗口映射到显示器分辨率的大小，此时鼠标最大活动的范围实际上是仍然维持在原本窗口大小的范围。操作游戏以外的窗口挺麻烦的想不到有什么好的方式。你如果有俩显示器你可以尝试把Misika拖动到副显示器使用

其实我想说的是鼠标离开翻译窗口范围后自动隐藏菜单栏
操作的话我一般也就换游戏后调下位置 问题不大

**Comment by AndromedaMelody** [comment]
Fix in 988c08a6b444b39ef1ced93eea0a0df6305b5486
