### ISSUE TITLE
优化程序设计

### ISSUE THREAD

**Issue by ricky8955555** [hanmin0822/MisakaTranslator#135]
无意中看到了这个项目，想法挺不错，但是程序设计上不太合理，鉴于本仓库 Star 数这么高，想要帮忙优化一下，但发现要改动的地方太多了。

我就提出下面几点建议吧（x）：

代码建议：
1. 尽量使用 `foreach`，避免使用 `for`。（如果需要获取 index 值，定义一个 `int`，在 `foreach` 块里进行 `i++`）
2. 向方法传递类型避免使用 `string` 或 `int`，或指定处理方法，应定义一个 `enum`，然后定义一个字典或方法，将 `enum` 转换成 API 所需的字符串形式（`enum` 可以在序列化时转换成 `int`，然后反序列化时可以转换回 `enum`）。
3. 在逻辑层方法遇到异常或意料之外的操作时，不应返回，应抛出异常。（除非该方法开头标注了 **Try**，如果为 `TryXxx` 方法，应当返回 `bool` 值，所需值使用 `out` 输出）
4. 更新信息使用 *json*, *xml* 之类的格式储存，避免使用取中间值方法（虽然效率高，但不太符合设计）。
5. 尽量使用 *Linq* 查询方法减少不必要的代码量。
6. 建议将窗体中的逻辑单独抽出成类，避免窗体中涉及逻辑过多导致窗体可维护性低问题。
7. 部分相同的逻辑建议抽离成方法，减少代码复用。
8. 能使用 `async`（异步） 方法的尽量使用，不要将异步转换成同步运行，避免 UI 线程阻塞所导致卡顿问题；HTTP 连接不使用 `System.Web` 命名空间下所提供的类进行操作，应使用 `System.Net.Http` 命名空间下所提供的类进行操作（`System.Net.Http` 下提供的操作支持异步）。
9. 遵循 [C# Coding Conventions](https://docs.microsoft.com/zh-cn/dotnet/csharp/fundamentals/coding-style/coding-conventions)（C# 编码约定）。
10. 若需返回多个值，但这些值之间并非有必要联系，定义新类型返回，不要使用 `List<T>`, `T[]`, `Tuple<T1, T2>` 之类的返回类型省事（比如说现 **master** 分支里的更新逻辑方法中，就返回的 `List<string>` 以达到同时返回最新版本及下载地址），这样省事并不方便日后维护。

修改参考：

- 更新逻辑的抽离及优化：
![image](https://user-images.githubusercontent.com/24487646/125452281-19417f32-f6a8-43a0-b613-559f01acda67.png)

- 使用 *Linq* 减少代码量：
![image](https://user-images.githubusercontent.com/24487646/125452336-8b9c39df-67ea-42e6-a08c-a043d7ce7da2.png)

- 使用 `string.Join(string, IEnuemrable<string>)` 方法及使用 `using` 实现资源释放 (`Dispose`) 优化，逻辑层意料之外操作直接抛出异常而不是返回 `null`，合理返回值：
![image](https://user-images.githubusercontent.com/24487646/125452652-5c18e048-1879-456a-95c0-5d3368071e82.png)

其他建议：
1. 建议使用 **.NET 5.0** 进行开发，可以带来更高的性能，也带来跨平台的可能性。
2. 增加模块接入功能，分离出核心，分离各功能为单独模块，减少程序的耦合度，降低程序主体的体积，也带来其他社区模块开发的可能性。

（暂时就先说这些吧，一时半会儿说不完全部建议）

**Comment by imba-tjd** [comment]
你可以PR，我可以review，但是Owner目前没有更新软件的想法。据我观察，更新是手动release的，本软件只是检测一下，不能自动下载，所以改更新模块我个人认为没啥必要。如果你愿意大改可以要Owner拉你作为collaborator。

跨平台，我不看好，本项目的逻辑太混乱了，遗留问题太多。

Core你可以用我的Fork。

**Comment by HumphreyDotSln** [comment]
有心了。
实际上很多优化都是我们考虑过的比如你说的模块化，你可以看看2.0版本之前的tag就能明白我们已经在一定程度上做过类似的努力的，但是本项目现在已经复杂到重写比重构更容易的程度了。
至于跨平台，有多少Galgame能在Windows之外的系统原生运行呢？

**Comment by spartawhy117** [comment]
> 有心了。
> 实际上很多优化都是我们考虑过的比如你说的模块化，你可以看看2.0版本之前的tag就能明白我们已经在一定程度上做过类似的努力的，但是本项目现在已经复杂到重写比重构更容易的程度了。
> 至于跨平台，有多少Galgame能在Windows之外的系统原生运行呢？

这个项目现在为啥不更新了呢？还是说去重新的新的翻译器了

**Comment by imba-tjd** [comment]
更新的逻辑就不改了，像之前说的，仅仅只是检测一下。
Process类改了，不过楼主的建议不太行，根据文档，Process需要Dispose。
ExportTextractorHistory仅仅在一开始判断textHooker is null可能不太够，这个textHooker是个static的变量，却又保有状态，所以这是个设计错误。现有的`catch (System.NullReferenceException)`估计就是遇到在中间使用textHooker的时候它变成null了。要修改就要大改，把流改成用using区别不大，所以干脆就不改了。
