### ISSUE TITLE
对HiDPI支持有问题

### ISSUE THREAD

**Issue by JeffersonQin** [hanmin0822/MisakaTranslator#138]
**关于哪一项功能**

屏幕OCR相关

**问题描述**

如果系统DPI缩放不是100%，则会出现该问题

**应用版本**

2.7

**系统信息**

Windows10 x64

**错误信息**

**附加截图**

![image](https://user-images.githubusercontent.com/30655701/129448657-e60b058c-07be-4a67-aa11-ea6c7298f05d.png)

绿色阴影是黑框，即不正常的表现。

解决方案：

可以参考我的个人项目[Ayase](https://github.com/JeffersonQin/Ayase)

我推断是使用P/Invoke调用Win32API时忘记考虑DPI缩放问题了。

我的解决方案：
- 封装`PrimaryScreen`: https://github.com/JeffersonQin/Ayase/blob/master/Ayase/ScreenLib/PrimaryScreen.cs
- 调用时: 
![image](https://user-images.githubusercontent.com/30655701/129448714-00e0875d-dca9-4147-ba0f-a375696339ce.png)

**Comment by JeffersonQin** [comment]
#9 #113

**Comment by imba-tjd** [comment]
有限时间内我没法改。我个人不用ocr，我看过一些高dpi的文章但还是不会。
如果有机会，我倾向于用Handy Contro提供的截图功能，因为它已经是本项目的依赖了（虽然理论上截图库不应依赖UI库）：https://handyorg.github.io/handycontrol/extend_controls/screenshot/

**Comment by JeffersonQin** [comment]
其实是这样的，截图您拿到的画面是对的，但是展示截图的窗口有dpi问题，所以才会出现黑边。

**Comment by JeffersonQin** [comment]
因为我之前的那个项目刚遇到这个问题，所以应该是这个问题。

**Comment by imba-tjd** [comment]
我不是Owner啊:joy:，我是Collaborator，那些代码不是我写的。我一直用hook，如果以后我要用到ocr了也许会研究吧，我只代表我自己现在不会改。

**Comment by JeffersonQin** [comment]
🤣好的好的（我也不太了解情况

**Comment by HumphreyDotSln** [comment]
稍微测试了一下，确实有点问题。
因为我之前修过这个功能，全屏截取应该是没问题的，获取Handle和获取窗口图像也都正常，所以猜测还是窗口定位出了问题。
遗憾的是目前也没时间继续修复了，阁下可以暂时先用全屏截取。

**Comment by luojunyuan** [comment]
说不定开启dpi aware简单地解决
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

**Comment by HumphreyDotSln** [comment]
> 说不定开启dpi aware可以简单地解决
> https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

这个是针对WinForms的，而且我们是直接调Win32 API实现的截图，并不是窗口本身显示有问题。

**Comment by imba-tjd** [comment]
WPF默认是System级别的DPI Aware，只要运行程序后所在屏幕没有改变DPI，就是DPI Aware的。更高级的Per Monitor和Per Monitor V2用于多屏幕，而且也不是开启后就自动支持了，要自己写回调事件代码。

**Comment by JeffersonQin** [comment]
@HumphreyDotSln @imba-tjd 确实 您说的是对的 其实只要在创建窗口时手动计算一下大小就行 辛苦了

**Comment by JeffersonQin** [comment]
@jsc723 我感觉不用这么麻烦 直接用p/invoke可以读到当前屏幕的dpi。我看到代码库里这方面的代码有写，只是在处理的时候忘记掉用了。
