### ISSUE TITLE
每次打开游戏都要重新选择Hook方法

### ISSUE THREAD

**Issue by OriginBo** [hanmin0822/MisakaTranslator#146]
**问题描述**

用默认Hook方式添加的游戏，每次重新打开游戏都会提示重新选择Hook方法

**应用版本**

V2.7

**系统信息**

Windows10 21H1

**附加截图**

![image](https://user-images.githubusercontent.com/56879486/136666023-2d402216-fdc3-45e8-a901-65749877d8e2.png)
![image](https://user-images.githubusercontent.com/56879486/136666035-5f2c2aab-6dda-46ec-8e3d-64ec0716b821.png)

**Comment by imba-tjd** [comment]
有一定几率不用重新选，我也不懂原理。
