### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by Refuse007ICU** [hanmin0822/MisakaTranslator#165]
==============System Info================
System:Microsoft Windows NT 10.0.19043.0
CurrentTime:2021/10/24 23:33
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.8.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.Reflection.TargetInvocationException
ExceptionSource:mscorlib
ExceptionMessage:调用的目标发生了异常。
ExceptionStackTrace:   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   在 System.Windows.Interop.HwndMouseInputProvider.HasCustomChrome(HwndSource hwndSource, RECT& rcClient)
   在 System.Windows.Interop.HwndMouseInputProvider.GetEffectiveClientRect(IntPtr hwnd)
   在 System.Windows.Interop.HwndMouseInputProvider.PossiblyDeactivate(IntPtr hwndCapture, Boolean stillActiveIfOverSelf)
   在 System.Windows.Interop.HwndMouseInputProvider.Dispose()
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
InnerExceptionStackTrace:System.ComponentModel.Win32Exception (0x80004005): 0x80070578
   在 Standard.HRESULT.ThrowIfFailed(String message)
   在 Standard.HRESULT.ThrowLastError()
   在 Standard.NativeMethods.GetWindowRect(IntPtr hwnd)
   在 System.Windows.Shell.WindowChromeWorker.GetEffectiveClientArea(RECT& rcClient)

**Comment by imba-tjd** [comment]
请用debug版复现一下，现在的错误日志没有任何一行具有实用意义

**Comment by imba-tjd** [comment]
改了，再试一下：https://wwa.lanzoui.com/i1AnLvxg9sh

**Comment by imba-tjd** [comment]
好了，真的是.NET Framework的问题，太恶心了。
下个版本会把翻译过程中的错误提示框改成警告框，这样能自动消失。TargetInvocationException也能不再出现。但是点那些信息框的叉无法关闭。

**Comment by imba-tjd** [comment]
fixed in 9cb34b80212b35fbc366ad590faab4ec32d5a386
