### ISSUE TITLE
調整顏色的功能有點問題

### ISSUE THREAD

**Issue by sky456757** [hanmin0822/MisakaTranslator#175]
**字體或背景顏色調整**

**问题描述**

調整顏色時按一下之後調整的視窗就會關閉，無法做出單擊以外的選擇動作（如拖曳）

**应用版本**

2.8

**系统信息**

Windows10 x64 

**错误信息**

無

**附加截图**

無

**Comment by imba-tjd** [comment]
fixed in e63c54484db9b898898d7874e6d419a5265cde31
