### ISSUE TITLE
希望能够提供控制全局通知的开关

### ISSUE THREAD

**Issue by zhouliangchen** [hanmin0822/MisakaTranslator#177]
### **在设置中提供选项，以启用/关闭全局通知**

全局通知能告知使用者引擎的报错信息，从而在引擎异常（例如联网失败，或是字符量不足）时能有效协助问题的解决。
但在部分场景下，这一全局通知是不必要的，且非常影响用户体验。

比如对游戏进行翻译时，引擎的翻译速度经常跟不上，导致大量“翻译取消“的报错信息；另外部分引擎，例如deepl是众所周知的慢，这一现象就更为严重。经常出现屏幕右侧被报错的信息占满的情况。然而，游戏翻译时，对少量的漏翻是不敏感的，这样的报错信息并不必要。

当前版本，全局通知信息还有在翻译过程中无法点叉、引起崩溃的问题；在暂时无法解决的前提下，提供开关，完全关掉通知也是可行的方法。

另外有一个小建议，在windows10下，系统自带有通知面板。完全可以采用系统api代替应用自己实现的通知功能

**Comment by imba-tjd** [comment]
> 提供开关，完全关掉通知

如果本项目是Python开发的，那将绝易，可惜Py不得

> 采用系统api

no plan

**Comment by imba-tjd** [comment]
关闭通知的功能添加了，虽然实现比较dirty。在“软件本体设置”中。
