### ISSUE TITLE
64位的游戏不能保存到主界面

### ISSUE THREAD

**Issue by shinslash** [hanmin0822/MisakaTranslator#178]
**问题描述**

如题，如nw.js封包的游戏，不确定是否64位的都不行，不过nw.js都是64位，最近很多游戏为了跨平台用了这个很烂的引擎。

**应用版本**

2.9

**系统信息**

Windows10 x64

**错误信息**

没有报错。

**Comment by imba-tjd** [comment]
我试了一下64位的winform，可以保存

**Comment by Astro357** [comment]
我用32位元的MisakaTranslator-WPF.exe 打开64位元的游戏 其中
ChooseGamePage.xaml.cs的
string filepath = ProcessHelper.FindProcessPath(GamePid);
裡面的
Process p = Process.GetProcessById(pid);
return p.MainModule.FileName;

'p.MainModule' 掷回 'System.ComponentModel.Win32Exception' 类型的例外状况
 32 位元处理序无法存取 64 位元处理序的模组。
所以filepath 会变成""
因此 Common.GameID 不会更新
会维持-1
所以不会储存到游戏库裡面

我编译成64位元的MisakaTranslator-WPF.exe  打开游戏一切正常
32位元的MisakaTranslator-WPF.exe打开游戏库裡面的64位元游戏一样有问题

**Comment by imba-tjd** [comment]
👍 怪不得。我就是用的64位的测试的

**Comment by imba-tjd** [comment]
emmm不对啊，我写了一个demo code，32位可以读取64位的进程…… 这个记事本肯定是64位的

![图片](https://user-images.githubusercontent.com/24759802/217462082-57ba6816-d655-4bcf-80f3-c3a1585a7a4f.png)

**Comment by Astro357** [comment]
你可能要确定一下你的建置平台目标是x86的  我选any cpu
debug 那边选x86 似乎他还是自动帮我编译成x64了

**Comment by imba-tjd** [comment]
emmm，用VS试出来了，之前用的是VSC+CSC。
System.ComponentModel.Win32Exception:“A 32 bit processes cannot access modules of a 64 bit process.”

**Comment by imba-tjd** [comment]
有啥建议么。我能想到一种方式是预编写一个x64的程序做这两件事。第二种方式是调用powershell。第三种方式是用wmic。tasklist可以过滤pid，但是无法输出游戏路径

**Comment by Astro357** [comment]
release里面包一个x64的 然后侦测一下游戏是不是64 是就教他们开x64的就好了

**Comment by imba-tjd** [comment]
确实，把本项目再编译出一个64位的发布，当用户玩64位的游戏时运行那个就行。

不过我还是决定用方法一，C#写64位命令行程序，输出MainModule.FileName，放到lib里。

用powershell和wmic可能导致已有的路径变化，不使用。

**Comment by imba-tjd** [comment]
太——痛——苦——了——

代码写完了，但是测试起来经常崩溃，想解决一个问题结果又发现了两个问题。

总之你们如果想测试可以下 https://github.com/imba-tjd/MisakaTranslator/actions/runs/4124498647 ，把release的dic和lib复制进去，再把这个放进lib：
[ProcessHelperExt.zip](https://github.com/hanmin0822/MisakaTranslator/files/10685986/ProcessHelperExt.zip)

分别测试没它时会不会崩溃、有它时会不会崩溃、能不能保存。

**Comment by imba-tjd** [comment]
fixed in 4f65fa592709760f9292a5ce47777dbb73d42353
