### ISSUE TITLE
tesseract5报错无法使用

### ISSUE THREAD

**Issue by gretino** [hanmin0822/MisakaTranslator#179]
**关于哪一项功能**
Tesseract5/TesseractOCR无法使用

**问题描述**

设置完tesseract5路径后在设置时使用OCR结果测试或是设置完后按快捷键截图OCR都会报错并且无结果。
设置为Tesseract5的报错：
![tesseract5Bug](https://user-images.githubusercontent.com/19314527/141939599-6b13d4ea-a92c-4a80-ba51-46a6e6d17e33.png)
设置为TesseractOCR的报错：
![tesseractOCRBug](https://user-images.githubusercontent.com/19314527/141939677-fd22bb6e-7540-419c-9ad1-254521b83026.png)

调整屏幕缩放为100%后重启并无改变。

命令行手动测试如tesseract5.exe input.tiff output 可以正常输出。

**应用版本**
2.9.2

**系统信息**
Windows11

**Comment by jsc723** [comment]
可能是因为没有权限保存临时文件，试试用管理员权限运行

**Comment by imba-tjd** [comment]
2.8能用吗

**Comment by gretino** [comment]
没换版本，刚刚重启后把本体从downloads文件夹里面移出来放到其他文件夹里面，ocr能用了，应该是和权限有关。

用了几次以后有另外一个报错，关闭重开软件后ocr恢复正常，影响不大。

又发现DeepL开始报错，有点莫名其妙。
DeepL:设置内的测试所有按钮都可以正常工作，使用hook可以正常翻译。使用ocr时会产生如下报错
![image](https://user-images.githubusercontent.com/19314527/142036845-6e9f9c75-a27c-412c-ae62-c253f47f000f.png)
我要不要再开一个issue?

**Comment by imba-tjd** [comment]
会不会是翻译频率太快？我想不出hook可以而ocr在这一步不行的原因，它们后半部分的逻辑是相同的。

**Comment by gretino** [comment]
又测试了一下，我认为并不是这个问题。ocr每按一次快捷键才尝试翻译一次，而且我在api网页上面token数也没有变化。

**Comment by gretino** [comment]
换了2.8版测试，又报了其他错还有log，可能是已经修了的就不贴这了。无法理解为什么2.9.2没log

**Comment by imba-tjd** [comment]
Tesseract5重新实现了。

deepl好像是因为free和pro的不能混用，本软件目前用的endpoint是free的，如果你用的是pro，就用不了。当然设计上可以加个选项切换，但是我不用deepl也注册不了，所以就懒得管了。如果有人要用就自己改源代码或者来PR吧。
