### ISSUE TITLE
使用免费ALAPI翻译接口，提示token未设置

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#180]
**问题描述**

最新版本，使用免费ALAPI翻译接口，提示token未设置。
腾讯翻译君的API似乎被官方取消了。用不了了。

**应用版本**
2.9.2

**系统信息**
Windows10 x64

**附加截图**
![image](https://user-images.githubusercontent.com/65847388/142027829-52f2db0b-43a1-4126-b7dc-360bd7cb7435.png)

**Comment by imba-tjd** [comment]
alapi没有免费版了吧。我觉得直接移除，要注册又是国内的，没必要用它。

腾讯翻译君的注册页面现在会跳到腾讯云机器翻译，但不代表翻译君用不了了，只是无法再注册。必须有已经注册的用户来反馈是否能用。从理论上来说，它们不会禁止已经注册的用户使用，否则会严重破坏已有应用。

**Comment by imba-tjd** [comment]
有用不了的现象吗

**Comment by hzl2010** [comment]
> 有用不了的现象吗

有，测试api，提示502 bad gateway。翻译也提示502

**Comment by imba-tjd** [comment]
https://github.com/hanmin0822/MisakaTranslator/commit/1b92a80fd8d326af3a84529a671ce48cd38a03d7

https://github.com/hanmin0822/MisakaTranslator/commit/5857e6b4e7ed1011352842282ddc6d6b750eb340
