### ISSUE TITLE
开启剪贴板更新后，翻译器的暂停按钮失效

### ISSUE THREAD

**Issue by Mintcolour** [hanmin0822/MisakaTranslator#182]
**关于哪一项功能**
从剪贴板获翻译

**问题描述**

**应用版本**

V2.9.2

**系统信息**

Windows11 x64

**错误信息**

![Snipaste_2021-11-18_15-52-37](https://user-images.githubusercontent.com/43575730/142374464-41a7d0e6-542a-4b52-8d20-ddab84d9179d.png)

**附加截图**

**Comment by imba-tjd** [comment]
fixed in https://github.com/hanmin0822/MisakaTranslator/commit/5741e32b8b277d13b1849996807c468e5d854438
