### ISSUE TITLE
會不會支援windows 11?

### ISSUE THREAD

**Issue by wbuffe** [hanmin0822/MisakaTranslator#183]
**关于哪一项功能**

**期望的效果**
會不會支援windows 11?

**Comment by imba-tjd** [comment]
我不认为现在的程序不支持win11。如果真的用不了，那答案就是不会，因为现存的维护者没空

**Comment by Mintcolour** [comment]
我是beta版的win11，hookfinder和翻译器本体可以正常使用。

**Comment by wbuffe** [comment]
> 我不认为现在的程序不支持win11。如果真的用不了，那答案就是不会，因为现存的维护者没空
辛苦了
