### ISSUE TITLE
 在日文文本的上方添加罗马音

### ISSUE THREAD

**Issue by castermoon** [hanmin0822/MisakaTranslator#19]
在日文文本的上方添加罗马音

**Comment by hanmin0822** [comment]
在翻译窗口的UI界面完善以后，会加入这个功能

**Comment by hanmin0822** [comment]
已经实现日文文本上方标注假名，罗马音功能根据用户反馈再考虑是否添加

**Comment by MoliereZhu** [comment]
现在的注音似乎是全部显示片假名，建议追加一个只在汉字上显示平假名的功能（MeCab分词应该也是默认这种），片假名很多人看起来还是难受了点。

**Comment by hanmin0822** [comment]
由于我本人不会日语，因此我也不知道Mecab提供的哪个字段是平假名，如果有想法的话可以修改代码中MecabHelper类库其中的相应字段即可

**Comment by yx-ChengAkemi** [comment]
片假名真的太折磨人了，建议换成罗马音
