### ISSUE TITLE
漫画翻译功能闪退、乱码

### ISSUE THREAD

**Issue by xlkgh** [hanmin0822/MisakaTranslator#196]
**问题描述**
使用离线TesseractOCR会闪退，无法进入漫画界面

使用Tesseract5会出现乱码，如图
![1](https://user-images.githubusercontent.com/14752195/151315673-999e7eec-31d8-435c-9c22-fb0cded0b272.png)
但是直接调用Tesseract5,翻译结果是正常的
![2](https://user-images.githubusercontent.com/14752195/151315880-20208ca4-4d4f-44fc-a261-0ced74686d33.png)
![3](https://user-images.githubusercontent.com/14752195/151315887-209729fd-1c41-4823-92a1-8acf29d03eae.png)

**应用版本**
2.10

**系统信息**
Windows10 x64 

**错误信息**
闪退并没有出现错误信息

**Comment by imba-tjd** [comment]
打开cmd，输入chcp，看结果是什么

**Comment by xlkgh** [comment]
把UTF-8勾上就正常了

![image](https://user-images.githubusercontent.com/14752195/151382907-1aa755e0-7641-4065-9074-e818e14a8e73.png)

**Comment by imba-tjd** [comment]
不……我本意是不应该勾这个选项，它的副作用太大
等我有空了来测试吧

**Comment by imba-tjd** [comment]
fixed in https://github.com/hanmin0822/MisakaTranslator/commit/71b7fd5749c5175a603b5fb401403468e94474a0

这命令行的行为太奇怪了，在ANSI环境下直接输出到控制台不乱码，但是用C#读取却又是U8的。我无法理解。
