### ISSUE TITLE
有道翻译结果与网页不同，质量差很多

### ISSUE THREAD

**Issue by ConcealedBlade** [hanmin0822/MisakaTranslator#199]
![微信图片_20220202225602](https://user-images.githubusercontent.com/63355926/152179555-3ca8a7c6-0418-465d-b4e3-bd8ca3f01f4b.png)
![微信截图_20220202225851](https://user-images.githubusercontent.com/63355926/152179573-2929d9e5-f958-4374-9fef-81b700c38d0d.png)
如图所示，第一张图第二条翻译为有道，是错误的，而网页翻译正确。
此外，希望下个版本加入有道api接口让用户自己填写。

**Comment by ConcealedBlade** [comment]
这两个接口还望作者修复一下，经过测试谷歌和有道翻译日文是最好的，完虐百度腾讯搜狗deepl

**Comment by imba-tjd** [comment]
有道老接口也即本程序用的接口是`/translate`，现在网页版的接口是`/translate_o`，需要鉴权。而且就算修好了，也是公共接口，用一小段时间就被禁了。如果有人愿意修可以PR，我不来研究。

谷歌我可以用。

**Comment by imba-tjd** [comment]
有道智云的API已经实现了，但是没有界面，想用的下 https://github.com/imba-tjd/MisakaTranslator/suites/5278858825/artifacts/163356269 ，修改settings.ini添加以下参数：

```
[YoudaoZhiyun]
YDZYAppId=xxx
YDZYAppKey=xxx
```

因为我自己没有注册，无法进行测试，不保证能用。如果不能用可以反馈。贡献代码可以往YDZY分支PR。

**Comment by fang10** [comment]
能不能提供下载的link？ 上面的link已失效了 感谢

**Comment by imba-tjd** [comment]
#238 添加了非公共API，感谢 @fang10 的贡献
