### ISSUE TITLE
似乎程序比较容易崩溃

### ISSUE THREAD

**Issue by CPCer** [hanmin0822/MisakaTranslator#20]
<-- 最好先在最新Beta版本中测试一下, 有些问题可能已经修复 -->
已确认
<-- 请先确保您已在issues里搜索过相关问题, 避免重复 -->
已搜索
<-- 请先确保您已阅读过教程中对此功能的相关说明, 其中一些细节说明可能就能解决您的问题 -->
……教程里好像没有提到崩溃的问题

**关于哪一项功能**
稳定性

**问题描述**
<-- 如何重现此问题, 在哪个功能遇到的问题 -->
以下场景容易崩溃：
1. 【智能处理】找到进程后直接点 “确认进程”（数10秒再点会好一些）
2. 在御坂妹妹反应时点击窗口任何位置（个人觉得可以增加一些~~御坂妹妹发电~~转圈的动画让用户稍候）
3. 调整翻译窗口字体颜色时选择【取色】，取外部颜色时
4. 【设置】左侧窗口点击过快
5. **设置OCR快捷键时如果按错（我的情况是``Ctrl`` + ``Alt``），程序会退出，而且保存错误的快捷键，使得程序彻底无法打开。除非确认问题后，修改配置文件。**

**应用版本**
<-- V2.0Beta4 -->

**系统信息**
Windows10 x64 1909

**错误信息**

我遇到的大部分问题并没有任何提示……

**附加截图**

**Comment by HumphreyDotSln** [comment]
2.0版本已经发布

**Comment by hanmin0822** [comment]
2.0刚放出时由于使用另一个上游源的原因导致容易崩溃，如今已经换用其他Hook方式，此外已添加错误日志记录。
