### ISSUE TITLE
日文竖版OCR崩溃

### ISSUE THREAD

**Issue by JohnnyJohnnny** [hanmin0822/MisakaTranslator#200]
漫画翻译使用tesseract5日文竖版OCR识别，选择文字之后就崩溃

==============System Info================
System:Microsoft Windows NT 6.1.7601 Service Pack 1
CurrentTime:2022/2/3 9:19
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.10.1.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.OutOfMemoryException
ExceptionSource:System.Drawing
ExceptionMessage:内存不足。
ExceptionStackTrace:   在 System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
   在 MisakaTranslator_WPF.ComicTranslator.ComicTransMainWindow.<InkCanvasMeasure_MouseDown>d__16.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 MisakaTranslator_WPF.App.Main()

**Comment by imba-tjd** [comment]
我不明白，崩溃前是真的内存不足吗？

**Comment by Quandong-Zhang** [comment]
> 我不明白，崩溃前是真的内存不足吗？

应该是，内存不足导致新栈申请失败了。
C语言没有GC,内存管理不好就容易泄露。

**Comment by imba-tjd** [comment]
可是bitmap是c#的class，分配到堆上啊，也有析构函数，内存不够时应该会自动gc的

**Comment by imba-tjd** [comment]
close as dup of #115
