### ISSUE TITLE
游戏A原本正常运行翻译可用  运行游戏B后再次尝试A崩溃闪退  重新导入设置运行A仍闪退  错误信息附上

### ISSUE THREAD

**Issue by 6516546** [hanmin0822/MisakaTranslator#205]
==============System Info================
System:Microsoft Windows NT 10.0.19043.0
CurrentTime:2022/2/10 13:01
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.10.1.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.FormatException
ExceptionSource:mscorlib
ExceptionMessage:输入字符串的格式不正确。
ExceptionStackTrace:   在 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   在 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   在 MisakaTranslator_WPF.Common.RepairFuncInit()
   在 MisakaTranslator_WPF.MainWindow.<StartTranslateByGid>d__22.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MisakaTranslator_WPF.MainWindow.<StartBtn_Click>d__24.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 MisakaTranslator_WPF.App.Main()

**Comment by imba-tjd** [comment]
把settings.ini发一下

**Comment by 6516546** [comment]
> 把settings.ini发一下

[OCR_All]
OCRsource=BaiduOCR
GlobalOCRLang=jpn

[BaiduOCR]
APIKEY=
SecretKey=

[Tesseract5OCR]
Path=C:\Program Files\Tesseract-OCR\tesseract
Mode=jpn
Args=-l jpn --psm 6

[Translate_All]
TransLimitNums=100
FirstTranslator=BaiduTranslator
SecondTranslator=NoTranslator

[Textractor]
AutoHook=True

[TranslateFormSettings]
LocX=356
LocY=488
SizeW=1287
SizeH=307
srcTextFont=微软雅黑
firstTransTextFont=微软雅黑
secondTransTextFont=微软雅黑
srcTextSize=15
firstTransTextSize=31
secondTransTextSize=32
opacity=15.8536585365854
firstTransTextColor=#FFC21C1C
secondTransTextColor=#FFFFFFFF

[Globalization]
Language=zh-CN

[BaiduTranslator]
appID=
secretKey=
百度翻译密钥我先隐藏了  我这边测试都是可用的 可以吗

**Comment by imba-tjd** [comment]
emmm抱歉，应该发RepairSettings.ini

**Comment by 6516546** [comment]
> emmm抱歉，应该发RepairSettings.ini

[RepairFun_RemoveSentenceRepeat]
FindCharNum=4

[RepairFun_RemoveSingleWordRepeat]
RepeatTimes=

**Comment by imba-tjd** [comment]
之前的代码没有重点考虑同时运行两个游戏的情形，目前Common.repairSettings是全局共享的，虽然不同游戏会从gameInfoList[gid]中读取，但是终归是有问题。治标的话就一次只运行一个游戏吧，如果本来就是只运行一个那就每次换游戏前都关闭本软件再开。

**Comment by 6516546** [comment]
> 之前的代码没有重点考虑同时运行两个游戏的情形，目前Common.repairSettings是全局共享的，虽然不同游戏会从gameInfoList[gid]中读取，但是终归是有问题。治标的话就一次只运行一个游戏吧，如果本来就是只运行一个那就每次换游戏前都关闭本软件再开。

理解错了 每次只运行了一个 并没有同时运行
现在我又尝试了一下 每次删除游戏重新添加设置一遍可以运行 但只要关闭后再打开就会崩溃

**Comment by imba-tjd** [comment]
你试试 https://github.com/imba-tjd/MisakaTranslator/suites/5245642884/artifacts/161496976，下好以后把老的lib文件夹复制进去

**Comment by 6516546** [comment]
textractor不存在或启动失败

**Comment by imba-tjd** [comment]
这就是为什么我要你复制lib……你100%没做这一步

**Comment by 6516546** [comment]
我理解错了 我以为是sqlite那个文件 我复制一下文件夹试试

**Comment by 6516546** [comment]
现在可以了 只是每次打开游戏都要跳出重新选择hook方法的设置向导

**Comment by 6516546** [comment]
> 这就是为什么我要你复制lib……你100%没做这一步
现在可以了 只是每次打开游戏都要跳出重新选择hook方法的设置向导

**Comment by imba-tjd** [comment]
有人提了，我没空研究
