### ISSUE TITLE
添加游戏出现全局无法解决异常

### ISSUE THREAD

**Issue by lklx520** [hanmin0822/MisakaTranslator#209]
**问题描述**
<添加游戏出现全局无法解决异常>

**应用版本**
<2.11>

**系统信息**
<Windows10 企业版LTSC -->

==============System Info================
System:Microsoft Windows NT 10.0.17763.0
CurrentTime:2022/3/2 4:35
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.11.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionName:MeCab.MeCabInvalidFileException
ExceptionSource:MeCab.DotNet
ExceptionMessage:dictionary file is broken[FileName:C:\Users\pal\Desktop\Debug\dic\sys.dic]
ExceptionStackTrace:   在 MeCab.Core.MeCabDictionary.Open(MemoryMappedFile mmf, String filePath) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/MeCabDictionary.cs:行号 112
   在 MeCab.Core.MeCabDictionary.Open(String filePath) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/MeCabDictionary.cs:行号 99
   在 MeCab.Core.Tokenizer.Open(MeCabParam param) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/Tokenizer.cs:行号 60
   在 MeCab.Core.Viterbi.Open(MeCabParam param) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/Viterbi.cs:行号 84
   在 MeCab.MeCabTagger.Create(MeCabParam param) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/MeCabTagger.cs:行号 118
   在 MecabHelperLibrary.MecabHelper..ctor() 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MecabHelperLibrary\MecabHelper.cs:行号 46
   在 MisakaTranslator_WPF.TranslateWindow..ctor() 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\TranslateWindow.xaml.cs:行号 79
   在 MisakaTranslator_WPF.GameGuideWindow.Next_Click(Object sender, RoutedEventArgs e) 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\GameGuideWindow.xaml.cs:行号 109
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 MisakaTranslator_WPF.GuidePages.CompletationPage.ConfirmBtn_Click(Object sender, RoutedEventArgs e) 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\GuidePages\CompletationPage.xaml.cs:行号 33
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

==============System Info================
System:Microsoft Windows NT 10.0.17763.0
CurrentTime:2022/3/2 4:35
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.11.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:MeCab.MeCabInvalidFileException
ExceptionSource:MeCab.DotNet
ExceptionMessage:dictionary file is broken[FileName:C:\Users\pal\Desktop\Debug\dic\sys.dic]
ExceptionStackTrace:   在 MeCab.Core.MeCabDictionary.Open(MemoryMappedFile mmf, String filePath) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/MeCabDictionary.cs:行号 112
   在 MeCab.Core.MeCabDictionary.Open(String filePath) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/MeCabDictionary.cs:行号 99
   在 MeCab.Core.Tokenizer.Open(MeCabParam param) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/Tokenizer.cs:行号 60
   在 MeCab.Core.Viterbi.Open(MeCabParam param) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/Core/Viterbi.cs:行号 84
   在 MeCab.MeCabTagger.Create(MeCabParam param) 位置 /export/home/kouji/Projects/MeCab.DotNet/MeCab.DotNet/MeCabTagger.cs:行号 118
   在 MecabHelperLibrary.MecabHelper..ctor() 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MecabHelperLibrary\MecabHelper.cs:行号 46
   在 MisakaTranslator_WPF.TranslateWindow..ctor() 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\TranslateWindow.xaml.cs:行号 79
   在 MisakaTranslator_WPF.GameGuideWindow.Next_Click(Object sender, RoutedEventArgs e) 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\GameGuideWindow.xaml.cs:行号 109
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 MisakaTranslator_WPF.GuidePages.CompletationPage.ConfirmBtn_Click(Object sender, RoutedEventArgs e) 位置 C:\Users\Administrator\Downloads\MisakaTranslator-master\MisakaTranslator-WPF\GuidePages\CompletationPage.xaml.cs:行号 33
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 System.Windows.Application.Run()
   在 MisakaTranslator_WPF.App.Main()

**Comment by imba-tjd** [comment]
> dictionary file is broken[FileName:C:\Users\pal\Desktop\Debug\dic\sys.dic]

感觉无法解决，这dic是nuget包自己生成的。要不你把显示原文关了。
