### ISSUE TITLE
能否使用Windows内置的ocr的API?

### ISSUE THREAD

**Issue by red-co** [hanmin0822/MisakaTranslator#213]
Windows10开始，Windows就内置了ocr功能，
这里有两个链接，一个是介绍的比较详细的博客，https://medium.com/dataseries/using-windows-10-built-in-ocr-with-c-b5ca8665a14e
另一个是ms官方的，
https://blogs.windows.com/windowsdeveloper/2016/02/08/optical-character-recognition-ocr-for-windows-10/

**Comment by AndromedaMelody** [comment]
由于新开了[forWin10](https://github.com/hanmin0822/MisakaTranslator/tree/forWin10)分支，并为现代化做了一些准备，所以可以Reopen这个建议，感谢支持。

**Comment by AndromedaMelody** [comment]
938d2dbf03ec44375d983dcb35eaac9ca9dc3bf8 已合并至 [develop](https://github.com/hanmin0822/MisakaTranslator/tree/develop) ，感谢您的建议。
