### ISSUE TITLE
最新版本小牛翻译作翻译源不能记录进splite数据库里

### ISSUE THREAD

**Issue by yui799** [hanmin0822/MisakaTranslator#214]
明明己经开启了人工翻译记录却没有小牛翻译后的文本，数据库里只有原文，只能文本翻译后在自定义人工翻译结果里点确定修改才能保留小牛的翻译文本，但是这太麻烦了，大佬能不能帮我解决一下

**Comment by yui799** [comment]
还有，御坂翻译器2.7版是不是不再支持小牛翻译了？习惯用老版本了

**Comment by imba-tjd** [comment]
move to #252

小牛应该支持吧
