### ISSUE TITLE
分行翻译选项无效,翻译结果不会拼接成一行

### ISSUE THREAD

**Issue by tbirdch** [hanmin0822/MisakaTranslator#216]
**关于哪一项功能**
分行翻译

**问题描述**

无论是否勾选'使用分行翻译',翻译结果均为分行显示。附图为baiduOCR+百度翻译英文的结果。

**应用版本**

2.11

**系统信息**

Windows11 x64

**附加截图**

![image](https://user-images.githubusercontent.com/20109280/163415323-15bd492a-59e7-4fbd-975d-58aa7c1e1d5f.png)

**Comment by tbirdch** [comment]
看了下代码似乎是hook模式才会去掉换行符；希望ocr模式也能增加这个功能。

**Comment by tbirdch** [comment]
用baiduOCR和Tesseract5一次ocr多行能正常识别，返回的结果是带换行符的。
我的意思是如果不勾选'使用分行翻译',ocr结果提交翻译前去掉换行符 或者替换为空格(源语言为英语时)

**Comment by tbirdch** [comment]
用baiduOCR和Tesseract5一次ocr多行能正常识别，返回的结果是带换行的，屏幕上显示几行就是几行。
我的意思是如果不勾选'使用分行翻译',ocr结果提交翻译前可以去掉换行符 或者替换为空格(源语言为英语时)

https://github.com/tbirdch/MisakaTranslator/commits/master 稍微改了下自己用着没问题(英翻中),本人菜鸟就不pull了...

**Comment by imba-tjd** [comment]
我明白你的意思了。但是为什么选择替换为空格而不是空呢

**Comment by tbirdch** [comment]
用空的话，英文前后行两个单词会粘在一起，日文大概没这问题....

**Comment by tbirdch** [comment]
英文上下行两个单词会粘在一起得用空格分开；日文的话应该用空好些。

**Comment by imba-tjd** [comment]
其实我觉得可以都用空格。
对于hook，假定源文本读到的\n是正确的，那替换成空格可避免因为没有标点，多句话变成单句话。
对于ocr，现在根本没有替换\n，那改成替换为空格不会使得现有情况更差。

**Comment by tbirdch** [comment]
日文书写方式是没有空格的。
当然都换空格也可以。日翻中时翻译引擎会忽略空格的(除了少部分专有名词)。

**Comment by tbirdch** [comment]
日文书写方式是没有空格的，日翻中时翻译引擎会忽略句中空格(除了少部分专有名词)。

当然\n统一换成空格也可以。和替换为空相比，只是偶尔碰到专有名词分两行写时翻不准而已。

无论如何合并行的结果至少会比目前更准确。

**Comment by imba-tjd** [comment]
你看这样行不行 https://github.com/imba-tjd/MisakaTranslator/commit/1c7e4ef10370ebe4bbb0f45bfa99177995e64422

以及需不需要我把你加入为该commit的author

**Comment by tbirdch** [comment]
是这样的，感谢大佬修复。 加author不必了，我只是提个建议。
