### ISSUE TITLE
关于tts项目的疑问

### ISSUE THREAD

**Issue by chocolatedesue** [hanmin0822/MisakaTranslator#217]
作者大大，请问tts项目如何做到能被其他项目引用的?

当我添加依赖后，cmd报错找不到speech.dll，但这个dll文件只有net4.7有。手动导入又说动态加载失败

麻烦您能给我一些指导，谢谢

**Comment by chocolatedesue** [comment]
或者说有没有直接在wpf下实现离线tts的方案?

不想折腾古董了

**Comment by chocolatedesue** [comment]
解决了，speechlib可以实现同样效果，speech库加了依赖后还要拷贝一份dill到文件exe位置

**Comment by sdtptj** [comment]
怎么说呢，我不是作者，我只是把作者的项目整了个分支自己留着。。。

chocolatedesue ***@***.***> 于 2022年4月18日周一 22:41写道：
