### ISSUE TITLE
进程崩溃

### ISSUE THREAD

**Issue by aitoo-1** [hanmin0822/MisakaTranslator#220]
==============System Info================
System:Microsoft Windows NT 10.0.19044.0
CurrentTime:2022/4/26 19:08
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.11.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionName:System.NullReferenceException
ExceptionSource:MisakaTranslator-WPF
ExceptionMessage:未将对象引用设置到对象的实例。
ExceptionStackTrace:   在 MisakaTranslator_WPF.TransWinSettingsWindow.TransWinSettingsWin_Closed(Object sender, EventArgs e)
   在 System.Windows.Window.OnClosed(EventArgs e)
   在 System.Windows.Window.WmDestroy()
   在 System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aitoo-1** [comment]
正常使用。点击🔒关闭，重新启动后报错崩溃，未重启

**Comment by imba-tjd** [comment]
fixed in https://github.com/hanmin0822/MisakaTranslator/commit/6570c401d72affa068619042d785fa2fa8a5b69f
