### ISSUE TITLE
原文本的文字隐藏及在主界面直接添加游戏

### ISSUE THREAD

**Issue by TTZSGAME** [hanmin0822/MisakaTranslator#221]
毕竟使用翻译器的人基本上都是不懂日语的吗，所以把原文本给放到翻译界面上来的话确实没设么用。所以能不能添加一个隐藏原文本的开关，这样看起来整体舒适一些。还有可以直接在软件界面上把以前运行过的游戏直接放到界面上来，这样就可以不用回到游戏安装目录下使用转区工具打开了。

**Comment by imba-tjd** [comment]
> 能不能添加一个隐藏原文本的开关

不是已经有吗？

> 在软件界面上把以前运行过的游戏直接放到界面上来

现在难道不是这样吗？
