### ISSUE TITLE
建议添加代理设置功能

### ISSUE THREAD

**Issue by kbr3NwSZ6kFq25** [hanmin0822/MisakaTranslator#222]
**关于哪一项功能**
建议添加代理设置功能，用来解决中国使用谷歌翻译慢的问题

**期望的效果**
可以设置socks和http代理

**Comment by imba-tjd** [comment]
谷歌翻译用的是北京谷翔的API，不会慢，真的慢就去找你的运营商，你添加代理到国外只会更慢。而且这是公共API，用个几分钟就因为太频繁限制无法使用了，不值得花精力改。

**Comment by xmcp** [comment]
目前DeepL的API限制了国内IP（会403），用美国IP才能正常使用。因此同求一个代理设置，如果实现起来不麻烦的话

**Comment by kbr3NwSZ6kFq25** [comment]
> 目前DeepL的API限制IP（会403，用美国IP实现正常使用国内代理设置）。

可以试试Proxifier

**Comment by NewBugger** [comment]
同求

**Comment by imba-tjd** [comment]
```c#
using System;
using System.Net;
using System.Net.Http;
using System.IO;

class Program
{
    static void Main()
    {
        var client = new HttpClient();
        string result = client.GetStringAsync("https://httpbin.org/get").Result;
        Console.WriteLine(result);

        var req = HttpWebRequest.CreateHttp("https://httpbin.org/get");
        var st = req.GetResponse().GetResponseStream();
        string result2 = new StreamReader(st).ReadToEnd();
        Console.WriteLine(result2);
    }
}
```

以上代码你们可以自己去试会不会用代理，看origin字段。事实上只要开全局就会自动用，所以你们开全局就完了。
pac是不可能支持的，那需要js的执行环境，只有浏览器才会支持pac。
这是两种自动使用代理的方式，如果在本项目内部再增加手动使用代理的设置，那倒是也可以，但是我不来做。

**Comment by NewBugger** [comment]
> > 目前DeepL的API限制IP（会403，用美国IP实现正常使用国内代理设置）。
> 
> 可以试试Proxifier

谢分享，这是其次的方法

**Comment by NewBugger** [comment]
> 如果在本项目内部再增加手动使用代理的设置，那倒是也可以，但是我不来做

因为没有写过 Windows 项目，请问这样有没有什么问题 https://github.com/NewBugger/MisakaTranslator/commit/e8bdea7822600032321c933047872f498e7fa703

**Comment by NewBugger** [comment]
> > 如果在本项目内部再增加手动使用代理的设置，那倒是也可以，但是我不来做
> 
> 因为没有写过 Windows 项目，请问这样有没有什么问题 [NewBugger@e8bdea7](https://github.com/NewBugger/MisakaTranslator/commit/e8bdea7822600032321c933047872f498e7fa703)

自己回复一下，已经用上了，有代理可以访问谷歌翻译。

**Comment by imba-tjd** [comment]
昂，反正会编程可以自己硬编码呗。做成可供用户配置的我不来做

**Comment by NewBugger** [comment]
pr 可以吗

**Comment by imba-tjd** [comment]
可以PR。但是你要明白需要做的事，是在设置页里增加一项设置代理的设置，然后修改所有访问网络的地方的代码使用代理；而且只能将设置从GUI层传给HTTP客户端层，不能反向引用GUI层的代码，否则那样不纯净。你能做出来那我没意见。不是硬编码那一处HttpClient使用127.0.0.1:1082的，你这样改可以自用。

**Comment by NewBugger** [comment]
#266 有能力的，actions 自动编译可以使用了
