### ISSUE TITLE
Windows11 闪退

### ISSUE THREAD

**Issue by red-co** [hanmin0822/MisakaTranslator#223]
2.11版本，当我确定ocr选取，测试结果的时候，就闪退了，

**Comment by imba-tjd** [comment]
如果你会C#编程，就开调试跑一遍。反正我是没法复现。闪退也没法修复。

**Comment by lsCoding666** [comment]
同样遇到这个问题 操作系统win11 闪退 ocr是tesseract

**Comment by lsCoding666** [comment]
md我知道是怎么回事了，通用设置中应该选择tesseract5而不是tesseract

**Comment by red-co** [comment]
谢谢，
