### ISSUE TITLE
cn域名打开后是个什么鬼

### ISSUE THREAD

**Issue by smallprogram** [hanmin0822/MisakaTranslator#232]
**关于哪一项功能**
https://misaka.galeden.cn/ 这个域名打开后让下载夸克？？
![image](https://user-images.githubusercontent.com/6050360/171542003-580dcf5d-8080-4bd3-ade1-e556670ebaea.png)

**Comment by jsc723** [comment]
官网已经没了

**Comment by q3128923436** [comment]
这个域名的证书是181ue.com的，而且早就过期了，要么是别劫持了，要么是域名过期解析的IP还是cloudflare的代理，
