### ISSUE TITLE
打开漫画文件夹时强制退出

### ISSUE THREAD

**Issue by YanHua06** [hanmin0822/MisakaTranslator#237]
**关于哪一项功能**
漫画翻译

**问题描述**

打开漫画文件夹时强制退出

**应用版本**

v2.11

**系统信息**

windows11 x64

**错误信息**

[2022-06-17 12-19-47.txt](https://github.com/hanmin0822/MisakaTranslator/files/8924503/2022-06-17.12-19-47.txt)

**附加截图**

**Comment by imba-tjd** [comment]
文件夹里只能有图片，不能有txt或其他东西

**Comment by imba-tjd** [comment]
因为`#271`包含的信息更多，更容易被人搜到。这边就反向关闭本issue了，留那个。
