### ISSUE TITLE
启动时提示数据库错误，使用时游戏设置未自动保存

### ISSUE THREAD

**Issue by WeiRi** [hanmin0822/MisakaTranslator#24]
**关于哪一项功能**

**问题描述**

1、启动时报错：“数据库访问错误”，提示没有game_library这个表
2、成功设置游戏配置后，选择退出翻译，在主界面没有保存此游戏的相关配置
**应用版本**

2.0正式版

**系统信息**

win10X64

**错误信息**

**附加截图**

**Comment by hanmin0822** [comment]
1.此错误应该很少见，如果出现可重启翻译器。
2.暂未制作实时更新，这个部分由另一位开发者负责

**Comment by CronusLM** [comment]
这应该是自己创建的MisakaGameLibrary.sqlite，而不是软件自动创建的，我之前调试scoop安装脚本创建完全空白的MisakaGameLibrary.sqlite就会报这个错误，且游戏设置不会保存

**Comment by AndromedaMelody** [comment]
1. Fix：https://github.com/hanmin0822/MisakaTranslator/commit/0b3cfc088f2caef51ea4a5b2b5404ac5c5da74d5#diff-d23b2389c3d7a65cb86843e1f2ce296f378085b975a7b46c19e6fbe805683b45R88
2. Deplicate：#30

**Comment by AndromedaMelody** [comment]
Fix in https://github.com/hanmin0822/MisakaTranslator/commit/99b056506acfdc7520e06b8a9548e410b7161f85#diff-d23b2389c3d7a65cb86843e1f2ce296f378085b975a7b46c19e6fbe805683b45
