### ISSUE TITLE
2.11 版无法使用百度翻译 API

### ISSUE THREAD

**Issue by linux40** [hanmin0822/MisakaTranslator#240]
**关于哪一项功能**
翻译功能

**问题描述**

配置好百度翻译 API 后，点击"测试翻译"，弹出"已取消一个任务"，点击"测试 API 认证"，弹出"ErrorID:54001"。

**应用版本**

2.11（2.7 正常）

**系统信息**

Windows10 x64

**错误信息**

见截图。

**附加截图**

![无标题](https://user-images.githubusercontent.com/31679941/174464746-38dd54d8-e6b0-41d7-8b6b-843fa90d8a14.png)

**Comment by imba-tjd** [comment]
can't reproduce. 2.7没问题就用2.7吧
