### ISSUE TITLE
OCR翻译向导第四项无法继续

### ISSUE THREAD

**Issue by Lost-MSth** [hanmin0822/MisakaTranslator#245]
**关于哪一项功能**
OCR翻译向导

**问题描述**
在第三步（设置触发键）中选择键盘触发，按下空格/回车键会自动进入第四步（选择翻译语言），但是后续无法进行任何操作（不是卡死，像是按钮不可用） 
选择鼠标触发则没有上述问题

**应用版本**
Release v2.11 [tag 2.11](https://github.com/hanmin0822/MisakaTranslator/tree/2.11)

**系统信息**
Windows 11 beta 22622.436

**错误信息**
没有抛出异常

> 顺便问一下，我选择OCR纯粹是因为hook导致游戏直接卡死，我搜了半天也没有看到一个相同问题，使用`MisakaHookFinder`注入也会卡死，游戏是半汉化的所以后半段需要翻译，翻译组似乎是利用`ZodGame.dll`进行汉化的，不清楚是不是hook撞了，有什么好解决办法吗？

**Comment by wzl19371** [comment]
Windows 10.0.19044的2.11版也有同样的问题
不过键盘依然可以用，可以通过键盘操作来完成OCR向导

**Comment by imba-tjd** [comment]
你们可以试试2.9.1有没有问题。大概率是 https://github.com/hanmin0822/MisakaTranslator/commit/f7cecd73e6a81c33df477775210574fb928418aa 造成的

**Comment by imba-tjd** [comment]
fixed in 27ea9f356fbeee4c6f4edc716b778547911e9563
