### ISSUE TITLE
狼头引擎Hook失败了，Textractor那边提供了解决方案，但似乎没有集成。

### ISSUE THREAD

**Issue by daiaji** [hanmin0822/MisakaTranslator#254]
https://github.com/Artikash/Textractor/issues/661#issuecomment-1038283059
RJ353573的体验版可复现。
集成一下看看？
然后有个大哥似乎是逆向了百度翻译网页版的API,现在百度限制了高级版和普通版的API调用配额。
https://github.com/TimLuo465/baidu-translate-api
这个好像是没有限制。

**Comment by AndromedaMelody** [comment]
Fix in 7373fecdd0702221954c2190a40b80c5015ad991
