### ISSUE TITLE
能不能在OCR设置里加一个识别内容输出到剪贴板的开关(check-btn)

### ISSUE THREAD

**Issue by windowstao** [hanmin0822/MisakaTranslator#257]
最好hook也加，所有的都加。
相当于把提取到的内容输出到剪贴板，让剪贴板做转接口。
百度翻译其实很差，比谷歌翻译差很多。而谷歌翻译的接口要自己配，公共的接口翻译质量也很差。
如果输出到剪贴板就可以切换到其他翻译接口了。
加个开关让识别的内容输出到剪贴板吧！！！

**Comment by imba-tjd** [comment]
https://github.com/hanmin0822/MisakaHookFinder

**Comment by windowstao** [comment]
什么意思？不能实现？
你也可以在翻译设置里加一个 “输出到剪贴板” 吧
翻译的方法
TranslateAsync里不是都有sourceText吗？
这个不就是提取到的源文字吗？
你新加一个翻译的方法为“输出到剪贴板” 
TranslateAsync的方法里写
Clipboard.SetText(sourceText);
这样不是可以吗？

**Comment by imba-tjd** [comment]
你会写程序可以自己改啊
