### ISSUE TITLE
去重的位置，在未设置用户自定义文件时，点击就报错

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#26]
**问题描述**
去重的位置，在未设置用户自定义文件时，点击就报错。

**应用版本**
V2.0

**系统信息**
Windows10 x64

**错误信息**

**Comment by hanmin0822** [comment]
没加错误判断，用户应该自行阅读相关说明后再使用这个功能

**Comment by asnml** [comment]
请问能提供下该功能的说明链接吗。Github wiki 和 官网 和 介绍视频都没提及该功能。

**Comment by hanmin0822** [comment]
> 请问能提供下该功能的说明链接吗。Github wiki 和 官网 和 介绍视频都没提及该功能。

Github Wiki已经收录，详见https://github.com/hanmin0822/MisakaTranslator/wiki/%E6%96%87%E6%9C%AC%E5%8E%BB%E9%87%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by asnml** [comment]
好的，谢谢。
