### ISSUE TITLE
Google TranslateCN已关闭，无法使用谷歌翻译接口

### ISSUE THREAD

**Issue by bychv** [hanmin0822/MisakaTranslator#260]
**关于哪一项功能**

建议更换为相应海外版本api
**问题描述**

**应用版本**

**系统信息**

**错误信息**

**附加截图**

**Comment by imba-tjd** [comment]
fixed in bca4ba2eb60d677589f2aa4197fc4772b806c933

You can still use the service in CN by adding `203.208.41.34 translate.googleapis.com` to hosts.

**Comment by imba-tjd** [comment]
好了，国内的ip好像都不行了。国外的ip可以看 https://zhuanlan.zhihu.com/p/576290326
