### ISSUE TITLE
打扰了，请问 develop 分支怎么编译

### ISSUE THREAD

**Issue by NewBugger** [hanmin0822/MisakaTranslator#265]
使用 GitHub actions 编译报错：
  C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file 'D:\a\MisakaTranslator\MisakaTranslator\Output\Misaka.WPF-Obj\Extensions\project.assets.json' doesn't have a target for 'net481/win7-x86'. Ensure that restore has run and that you have included 'net481' in the TargetFrameworks for your project. You may also need to include 'win7-x86' in your project's RuntimeIdentifiers. [D:\a\MisakaTranslator\MisakaTranslator\Misaka.WPF\Misaka.WPF.csproj]

https://github.com/NewBugger/MisakaTranslator/actions/runs/3498377370/jobs/5858835253

感谢 @AndromedaMelody

**Comment by AndromedaMelody** [comment]
需要.Net Framework 4.8.1 development tool、MSIX packaging tools、MSVC v143 build tools、Windows SDK 22621。为了使用Win10以来的现代化设施，故抛弃了对Win7的支持，但是由于近期甚至明年时间有限，进度很慢。
因为自保含一个.Net Core Runtime体积太大，所以取消[使用.Net 6/7的计划](https://github.com/AndromedaMelody/MisakaTranslator/tree/block/net6)，.Net Framework 4.8.1也正好支持了ARM64设备。
切换到C++构建[新界面](https://github.com/AndromedaMelody/MisakaTranslator/tree/dev/ui)是一个大工程，于是develop分支目前处于一个相当尴尬的状态。。。
![Screenshot 2022-11-19 105725](https://user-images.githubusercontent.com/57533055/202831080-75017a0c-9938-4f57-9cf9-a377bc6661dd.png)

**Comment by NewBugger** [comment]
感谢详细的回复

>> develop的CI已经被暂时移除，因为原有的CI已经不能满足现有的改变

请问 https://github.com/AndromedaMelody/MisakaTranslator/commit/c89d47b935afe741600e4dca83b25f126909eaa2 直到哪个 commit 还有效，到 https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a 还有效吗

**Comment by NewBugger** [comment]
> 感谢详细的回复
> 
> > > develop的CI已经被暂时移除，因为原有的CI已经不能满足现有的改变
> 
> 请问 [AndromedaMelody@c89d47b](https://github.com/AndromedaMelody/MisakaTranslator/commit/c89d47b935afe741600e4dca83b25f126909eaa2) 直到哪个 commit 还有效，到 [AndromedaMelody@7fac13a](https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a) 还有效吗

能打开了，请问怎么安装 Windows runtime ocr 组件

**Comment by AndromedaMelody** [comment]
> > 感谢详细的回复 @AndromedaMelody
> > > > develop的CI已经被暂时移除，因为原有的CI已经不能满足现有的改变
> > 
> > 
> > 请问 [AndromedaMelody@c89d47b](https://github.com/AndromedaMelody/MisakaTranslator/commit/c89d47b935afe741600e4dca83b25f126909eaa2) 直到哪个 commit 还有效，到 [AndromedaMelody@7fac13a](https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a) 还有效吗
> 
> 能打开了，请问怎么安装 Windows runtime ocr 组件
> 
> “ocr 预览可以正常工作，ocr 结果测试报错 请安装 ocr 组件，winrtocr api 异常”

输入法设置那里添加日语

**Comment by NewBugger** [comment]
> > > 感谢详细的回复 @AndromedaMelody
> > > > > develop的CI已经被暂时移除，因为原有的CI已经不能满足现有的改变
> > > 
> > > 
> > > 请问 [AndromedaMelody@c89d47b](https://github.com/AndromedaMelody/MisakaTranslator/commit/c89d47b935afe741600e4dca83b25f126909eaa2) 直到哪个 commit 还有效，到 [AndromedaMelody@7fac13a](https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a) 还有效吗
> > 
> > 
> > 能打开了，请问怎么安装 Windows runtime ocr 组件
> > “ocr 预览可以正常工作，ocr 结果测试报错 请安装 ocr 组件，winrtocr api 异常”
> 
> 输入法设置那里添加日语

但是我一直都有，也重启过了
![image](https://user-images.githubusercontent.com/41441631/202850473-487f726b-417c-4f90-9475-5413ee3654a3.png)

**Comment by AndromedaMelody** [comment]
> 但是我一直都有，也重启过了 ![image](https://user-images.githubusercontent.com/41441631/202850473-487f726b-417c-4f90-9475-5413ee3654a3.png)

`DISM.exe /Online /Add-Capability /CapabilityName:Language.OCR~~~ja-JP~0.0.1.0`

**Comment by NewBugger** [comment]
> > 但是我一直都有，也重启过了 !
> 
> `DISM.exe /Online /Add-Capability /CapabilityName:Language.OCR~~~ja-JP~0.0.1.0`

非常感谢，ocr 有了

但遇到了新问题：在添加游戏菜单里测试 ocr 能使用（虽然识别的准确率接近为 0），添加区域后使用就会导致翻译器崩溃退出，不知道怎么抓日志

**Comment by AndromedaMelody** [comment]
> 但遇到了新问题：在添加游戏菜单里测试 ocr 能使用（虽然识别的准确率接近为 0），添加区域后使用就会导致翻译器崩溃退出，不知道怎么抓日志

Win内置OCR在黑底白字识别准确率还行，得要先图像处理。
添加区域可否细说复现步骤。log日志我不清楚您基于哪个commit编译的，因为换过存放目录。

**Comment by NewBugger** [comment]
构筑是 https://github.com/newbuggerorg1/MisakaTranslator/actions/runs/3503113158，版本是 https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a

遇到的问题是不管哪种模式，都会崩溃闪退

**Comment by AndromedaMelody** [comment]
> 构筑是 https://github.com/newbuggerorg1/MisakaTranslator/actions/runs/3503113158 ，版本是 [AndromedaMelody@7fac13a](https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a)
> 
> 遇到的问题是不管哪种模式，都会崩溃闪退

lib文件夹复制进去了吗，lib文件夹里的第三方依赖不会随源码构建，需要从release的版本复制。
develop分支后面会尽可能清除掉这部分，目前最新的commit已经清掉了不少第三方依赖

**Comment by NewBugger** [comment]
> > 构筑是 https://github.com/newbuggerorg1/MisakaTranslator/actions/runs/3503113158 ，版本是 [AndromedaMelody@7fac13a](https://github.com/AndromedaMelody/MisakaTranslator/commit/7fac13a50f0c79c3a684eb882083a3538176109a)
> > 遇到的问题是不管哪种模式，都会崩溃闪退
> 
> lib文件夹复制进去了吗，lib文件夹里的第三方依赖不会随源码构建，需要从release的版本复制。 develop分支后面会尽可能清除掉这部分，目前最新的commit已经清掉了不少第三方依赖

这个是有的，覆盖了 master release 版本使用的

**Comment by NewBugger** [comment]
更新对比案例：我把 win ocr 移植到原 master 分支，刚已成功用上 构筑和代码在 https://github.com/newbuggerorg1/MisakaTranslator/actions/runs/3504264790

**Comment by AndromedaMelody** [comment]
> 更新对比案例：我把 win ocr 移植到原 master 分支，刚已成功用上 构筑和代码在 https://github.com/newbuggerorg1/MisakaTranslator/actions/runs/3504264790
> 
> 识别率感人啊 微软 ![image](https://user-images.githubusercontent.com/41441631/202861699-9fc13c21-001a-4bd2-89ce-cfafe11323bc.png)

如果可以的话 希望可以提供develop分支下的logs文件夹的日志txt内容 因为我这里暂时无法复现相关问题。（添加区域是指用LE转区吗

**Comment by NewBugger** [comment]
> > > 但是我一直都有，也重启过了 !
> > 
> > 
> > `DISM.exe /Online /Add-Capability /CapabilityName:Language.OCR~~~ja-JP~0.0.1.0`
> 
> 非常感谢，ocr 有了
> 
> 但遇到了新问题：在添加游戏菜单里测试 ocr 能使用（虽然识别的准确率接近为 0），添加区域后使用就会导致翻译器崩溃退出，不知道怎么抓日志
> 
> 补充：试了一圈 ocr 和 hook 模式都是这样，崩溃闪退

是我没说清楚，这里的添加区域就是添加游戏选择 ocr 区域的菜单，在这个菜单里识别文字不会闪退，但是添加游戏完毕后开始翻译就会卡住、然后闪退

我看过 logs 目录，这个目录是当出现“出现严重错误需要退出”这个程序自有报错窗口时才会输出日志，我的闪退是没有日志文件输出，所以 logs 里面没有

**Comment by AndromedaMelody** [comment]
> 是我没说清楚，这里的添加区域就是添加游戏选择 ocr 区域的菜单，在这个菜单里识别文字不会闪退，但是添加游戏完毕后开始翻译就会卡住、然后闪退
> 
> 我看过 logs 目录，这个目录是当出现“出现严重错误需要退出”这个程序自有报错窗口时才会输出日志，我的闪退是没有日志文件输出，所以 logs 里面没有

感谢 虽然暂时没有复现 但相关问题会留意。

（微软的内置OCR想要准确识别还是有点苛刻的 我测试的结果是只有白底黑字这种高对比相对比较靠谱

**Comment by AndromedaMelody** [comment]
develop分支现在已经移除，部分commits后续将逐渐合并至master。感谢 @NewBugger 支持

**Comment by NewBugger** [comment]
> develop分支现在已经移除，部分commits后续将逐渐合并至master。感谢 @NewBugger 支持

开发完毕了吗

**Comment by AndromedaMelody** [comment]
开发终止，因为开发维护成本越来越高，合并上游越来越困难，并且缺少足够的时间和精力，使用C++和XAML Islands重构缺乏必要性，其余部分可以合并master的，无需另立分支
