### ISSUE TITLE
CTRL一定几率会导致软件闪退

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#27]
**关于哪一项功能**
按CTRL经常导致软件闪退。
**期望的效果**
建议学习vnr，不翻译字数过多或速度过快的文字。长于120字就不翻译就ok了

**Comment by hanmin0822** [comment]
2.1版本已添加字数翻译长度限制，速度限制等还在制作，目前提供了暂停/恢复功能用于存档和快进游戏时使用。
