### ISSUE TITLE
打开漫画翻译报错退出，log显示ExceptionMessage:参数无效。

### ISSUE THREAD

**Issue by 315923876** [hanmin0822/MisakaTranslator#271]
**关于哪一项功能**

**问题描述**

打开翻译器后，点击漫画翻译后报错。BaiduOCR，BaidufanyiOCR，Tesseract5均出现，TesseractOCR点漫画翻译直接闪退，已经填写百度OCR API，API验证正常

**应用版本**

2.11，2.11Debug，2.8

**系统信息**

Windows10 x64

**错误信息**

==============System Info================
System:Microsoft Windows NT 10.0.19045.0
CurrentTime:2022/12/11 20:39
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.11.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionName:System.ArgumentException
ExceptionSource:System.Drawing
ExceptionMessage:参数无效。
ExceptionStackTrace:   在 System.Drawing.Bitmap..ctor(String filename)
   在 MisakaTranslator_WPF.ComicTranslator.ComicTransMainWindow.ShowPictrue(String path)
   在 MisakaTranslator_WPF.ComicTranslator.ComicTransMainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**附加截图**

![6YN~37BS(0UW(KH)98MP4)P](https://user-images.githubusercontent.com/115673942/206905685-de0e9270-b120-4faa-8cff-3d00b04fc35d.png)

**Comment by imba-tjd** [comment]
see #237

**Comment by 315923876** [comment]
> see #237

谢谢，已经解决

**Comment by imba-tjd** [comment]
别关啊:joy:，确实属于bug，等未来某一天解决吧

**Comment by afengaf** [comment]
> 见#237

兄弟还在么，为什么我的文件夹里全是图片但还是会弹出这个错误啊

**Comment by imba-tjd** [comment]
可能有隐藏文件吧

**Comment by afengaf** [comment]
> 可能有隐藏文件吧

我已经开启了显示隐藏文件，但是文件夹里确实只有jpg

**Comment by afengaf** [comment]
还有就是对比上面的报错文件，我的文件最下方多了两行
在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

> > 可能有隐藏文件吧
> 
> 我已经开启了显示隐藏文件，但是文件夹里确实只有jpg

**Comment by afengaf** [comment]
> 可能有隐藏文件吧

请问大佬怎么解决呢

**Comment by imba-tjd** [comment]
图片格式是什么？把图片删到只剩一张，看还会不会报错，如果还会，就把文件夹压缩一下发上来

**Comment by afengaf** [comment]
> 图片格式是什么？把图片删到只剩一张，看还会不会报错，如果还会，就把文件夹压缩一下发上来
我试过了，图片都是jpg格式，但是很奇怪，把两本漫画分别放进同一个文件夹，一部可以成功，一部会报错，我试了试我自己下载的漫画，有的就可以导入翻译，有的就不行会报错，漫画都是jpg格式
