### ISSUE TITLE
开启软件时报错

### ISSUE THREAD

**Issue by Hentai-Kuroko** [hanmin0822/MisakaTranslator#277]
==============System Info================
System:Microsoft Windows NT 10.0.18363.0
CurrentTime:2023/2/12 21:16
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.12.2.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.ArgumentException
ExceptionSource:mscorlib
ExceptionMessage:要在此字符串中进行分析，必须指定有效信息。
ExceptionStackTrace:   在 System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   在 System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   在 System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   在 System.Enum.Parse(Type enumType, String value)
   在 KeyboardMouseHookLibrary.GlobalHotKey.RegisterHotKeyByStr(String str, IntPtr handle, HotKeyCallBackHandler callback) 位置 D:\a\MisakaTranslator\MisakaTranslator\KeyboardMouseHookLibrary\GlobalHotKey.cs:行号 101
   在 MisakaTranslator_WPF.MainWindow.MainWindow_SourceInitialized(Object sender, EventArgs e) 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\MainWindow.xaml.cs:行号 142
   在 System.EventHandler.Invoke(Object sender, EventArgs e)
   在 System.Windows.Window.OnSourceInitialized(EventArgs e)
   在 HandyControl.Controls.Window.OnSourceInitialized(EventArgs e)
   在 System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   在 System.Windows.Window.CreateSourceWindowDuringShow()
   在 System.Windows.Window.SafeCreateWindowDuringShow()
   在 System.Windows.Window.ShowHelper(Object booleanBox)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 System.Windows.Application.Run()
   在 MisakaTranslator_WPF.App.Main()

![QQ截图20230212212405](https://user-images.githubusercontent.com/120932412/218310893-151446e6-9702-4689-8a29-0d2a78d0d0ef.png)

很久没有使用了，打开2.11版本时跳出更新信息并报错，下载最新2.12.2版本后仍报错

**Comment by imba-tjd** [comment]
把原来的配置删了吧

**Comment by Hentai-Kuroko** [comment]
解决了，谢谢

>
