### ISSUE TITLE
Total sentence number not match, please check your patch.

### ISSUE THREAD

**Issue by logicrovery** [hanmin0822/MisakaTranslator#280]
前面是正常使用的，突然在开启时显示全局错误。
[2023-03-03 12-47-45.txt](https://github.com/hanmin0822/MisakaTranslator/files/10878281/2023-03-03.12-47-45.txt)
==============System Info================
System:Microsoft Windows NT 10.0.22621.0
CurrentTime:2023/3/3 12:47
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.12.2.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.Exception
ExceptionSource:TranslatorLibrary
ExceptionMessage:Total sentence number not match, please check your patch.
ExceptionStackTrace:   在 TranslatorLibrary.ArtificialTranslator.TranslatorInit(String patchPath, String param2) 位置 D:\a\MisakaTranslator\MisakaTranslator\TranslatorLibrary\ArtificialTranslator.cs:行号 135
   在 MisakaTranslator_WPF.TranslateWindow.TranslatorAuto(String translator) 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\TranslateWindow.xaml.cs:行号 266
   在 MisakaTranslator_WPF.TranslateWindow..ctor() 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\TranslateWindow.xaml.cs:行号 108
   在 MisakaTranslator_WPF.MainWindow.<StartTranslateByGid>d__22.MoveNext() 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\MainWindow.xaml.cs:行号 271
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 MisakaTranslator_WPF.MainWindow.<StartBtn_Click>d__24.MoveNext() 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\MainWindow.xaml.cs:行号 285
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 System.Windows.Application.Run()
   在 MisakaTranslator_WPF.App.Main()

**Comment by imba-tjd** [comment]
如果你确实是主动使用人工翻译，那手动编辑一下翻译记录文件，使得中文和日文条目数匹配。

如果你不懂人工翻译是什么，那你为什么要用？

**Comment by logicrovery** [comment]
抱歉，明白了。
