### ISSUE TITLE
只显示原文，即使已经配置了来自百度的API

### ISSUE THREAD

**Issue by zeiyu314** [hanmin0822/MisakaTranslator#289]
**关于哪一项功能**

**问题描述**

直接使用，游戏是光翼战姬

**应用版本**

v2.12.2
**系统信息**

win11

**错误信息**

没有任何错误抛出，但是只显示了源文字和注音，并未显示翻译，使用了百度的API，测试通过

**附加截图**

<img width="536" alt="image" src="https://user-images.githubusercontent.com/44489550/230624717-4991d32f-6ce9-4ea9-902d-de5c2ce2eb56.png">

**Comment by imba-tjd** [comment]
设置过一遍，或者看看视频怎么用
