### ISSUE TITLE
关闭游戏后，再关闭翻译框一定几率报错。

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#29]
**问题描述**
游戏运行时，关闭翻译框大概率直接闪退。
游戏关闭后，关闭翻译框报错。

**应用版本**
V2.0

**系统信息**

错误信息
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/5/24 23:44
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.0.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionSource:
ExceptionMessage:未将对象引用设置到对象的实例。
ExceptionStackTrace:

**Comment by hanmin0822** [comment]
正确的退出方法应该是先退出翻译框，再退出游戏。

**Comment by hzl2010** [comment]
> 正确的退出方法应该是先退出翻译框，再退出游戏。

游戏运行中，退出翻译框，大概率不报错直接闪退

**Comment by hanmin0822** [comment]
2.2版本已经Release，尝试使用，出现bug的概率小很多
