### ISSUE TITLE
x86 TextractorCLI无法正常启动

### ISSUE THREAD

**Issue by LovesAsuna** [hanmin0822/MisakaTranslator#301]
**关于哪一项功能**
Textrator

**问题描述**
x86的TextratorCLI突然不能使用了，直接运行会提示应用程序无法正常启动。x64倒是可以，但是x64对游戏是无法提取的

**应用版本**
V2.12.2

**系统信息**
Windows 11 x64

**错误信息**
![image](https://github.com/hanmin0822/MisakaTranslator/assets/32810896/a0c8c509-1c5b-4472-b973-26b0afc31df0)

**附加截图**
![image](https://github.com/hanmin0822/MisakaTranslator/assets/32810896/2f97b97c-da68-4d4d-9939-a6343d4f4558)

**Comment by LovesAsuna** [comment]
猜测是Windows 11系统更新把某些环境弄坏了

**Comment by imba-tjd** [comment]
本项目调用的外部exe，我觉得你直接使用普通的TextractorCLI.exe命令行看看能不能用吧

**Comment by LovesAsuna** [comment]
截图就是单独运行的结果

**Comment by imba-tjd** [comment]
那没啥好办法啊……你去跟 https://github.com/Artikash/Textractor 反馈嘛
