### ISSUE TITLE
有没有可能自定义api之类的，而不是局限于内置的几个

### ISSUE THREAD

**Issue by zxc980927** [hanmin0822/MisakaTranslator#303]
自定义请求地址，请求参数，header,body.....，然后请求映射，返回映射指定字段

**Comment by zxc980927** [comment]
有些公共的网页翻译，用apifox试了下请求，能请求到结果

**Comment by zxc980927** [comment]
就算不行，也可以自己本地搭，再调用第三方api，至少不用只能用某些了

**Comment by imba-tjd** [comment]
会js就去用 https://github.com/project-yuki/YUKI 呗。你这种情形太局限了，使用者必须不会C#编程但会另一种语言编程、不用别的翻译器就要用本项目。做法就是本翻译器调用一下外部程序，写入stdin，外部程序处理后读取stdout，再继续处理。没啥意义。
