### ISSUE TITLE
百度翻译API无法正常工作

### ISSUE THREAD

**Issue by poly000** [hanmin0822/MisakaTranslator#306]
**关于哪一项功能**

**问题描述**

填入 secret key 和 api key

**应用版本**

2.13.0

**系统信息**

windows11 x64 22631.2050

**错误信息**

do not use the endpoint ai.baidu.com

**附加截图**

![image](https://github.com/hanmin0822/MisakaTranslator/assets/34085039/fd570d8c-6380-4ecb-a7a5-c899e7b24285)

**Comment by imba-tjd** [comment]
你修改后测试过了吗

**Comment by poly000** [comment]
> 你修改后测试过了吗

还没，但是sign方式和参数都没有改变

**Comment by imba-tjd** [comment]
其实这是不可能的。那句报错是本项目代码主动发出的，起因是用户分不清`ai.baidu.com`和`fanyi.baidu.com`，检测原理是判断某一输入框内容的长度是否是24位。你做的修改是不会影响那些报错逻辑的

**Comment by poly000** [comment]
> 其实这是不可能的。那句报错是本项目代码主动发出的，起因是用户分不清`ai.baidu.com`和`fanyi.baidu.com`，把一个网站的东西填到另一个里，检测原理是判断某一输入框内容的长度是否是24位。你做的修改是不会影响那些报错逻辑的

诶。。

**Comment by poly000** [comment]
可能是冲多了的时候开的issue（ 抱歉
