### ISSUE TITLE
全局无法解决的异常

### ISSUE THREAD

**Issue by Setchan1111** [hanmin0822/MisakaTranslator#308]
**问题描述**
启动软件立刻跳出错误，确认后软件关闭

**应用版本**
2.12.2

**系统信息**

windows 10 x64

**错误信息**
==============System Info================
System:Microsoft Windows NT 10.0.19044.0
CurrentTime:2023/7/31 22:50
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.12.2.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionName:System.TypeInitializationException
ExceptionSource:PresentationCore
ExceptionMessage:“System.Windows.Automation.Peers.AutomationPeer”的类型初始值设定项引发异常。
ExceptionStackTrace:   在 System.Windows.Automation.Peers.AutomationPeer.RaiseFocusChangedEventHelper(IInputElement newFocus)
   在 System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   在 System.Windows.Input.KeyboardDevice.PostProcessInput(Object sender, ProcessInputEventArgs e)
   在 System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.PossiblyDeactivate(IntPtr hwndFocus)
   在 System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
InnerExceptionStackTrace:System.TypeLoadException: 程序集“PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”中的类型“MS.Internal.Automation.SelectionProviderWrapper”的方法“GetSelection”没有实现。
   在 System.Windows.Automation.Peers.AutomationPeer.Initialize()
   在 System.Windows.Automation.Peers.AutomationPeer..cctor()

**Comment by imba-tjd** [comment]
I don't think there is much I can do.
https://github.com/dotnet/wpf/issues/8056

**Comment by lindexi** [comment]
现在我也不知道这个问题的原因是什么以及复现的步骤是什么

**Comment by StudyForFreedom** [comment]
> 现在我也不知道这个问题的原因是什么以及复现的步骤是什么


WIN10 22H2 系统，安装KB5011048补丁 以后就会出现

**Comment by lindexi** [comment]
> > 现在我也不知道这个问题的原因是什么以及复现的步骤是什么
> 
> WIN10 22H2 系统，安装KB5011048补丁 以后就会出现

确实有人和我报告过这个补丁有问题，请看 https://github.com/dotnet/wpf/issues/8056#issuecomment-1694154568

**Comment by StudyForFreedom** [comment]
> > > 现在我也不知道这个问题的原因是什么以及复现的步骤是什么
> > 
> > 
> > WIN10 22H2 系统，安装KB5011048补丁 以后就会出现
> 
> 确实有人和我报告过这个补丁有问题，请看 [dotnet/wpf#8056 (comment)](https://github.com/dotnet/wpf/issues/8056#issuecomment-1694154568)

好像目前的解决措施只能卸载这个补丁，但是我自己尝试安装这个版本的系统并主动去官网打上这个补丁并没有出现这种情况，以后避免这种情况可能得升级.net并使用独立部署了

**Comment by lindexi** [comment]
@StudyForFreedom 似乎不是单独一个补丁就能出现问题的。更细节的问题我没有调试，就还不了解情况
