### ISSUE TITLE
触发原因不明，但直接放导致hook功能完全失效

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#31]
**关于哪一项功能**
同步hook功能。

**问题描述**
未知如何触发，自动开始功能有可能触发。
触发后hook功能完全失效，一自动同步游戏hook就报错。
连用同样hook工具的Yuki也会导致无法同步hook而报错。
（但是有小几率可以通过重新hook向导，进行同步游戏。）
只能重启才能恢复。

**应用版本**
V2.0

**系统信息**
Windows10 x64

**错误信息**
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/5/24 23:56
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.0.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionSource:TextHookLibrary
ExceptionMessage:外部组件发生异常。
ExceptionStackTrace:   在 TextHookLibrary.TextHostLib.DetachProcess(UInt32 processId)
   在 TextHookLibrary.TextHookHandle.Finalize()

==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/5/24 23:56
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.0.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionSource:TextHookLibrary
ExceptionMessage:无法复制texthook.dll或texthost.dll，请重启游戏和翻译器后再试！
ExceptionStackTrace:   在 TextHookLibrary.TextHookHandle.Init(Boolean x86)
   在 MisakaTranslator_WPF.MainWindow.StartTranslateBygid(Int32 gid)
   在 MisakaTranslator_WPF.MainWindow.StartBtn_Click(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by hanmin0822** [comment]
2.0版本在出现 无法复制texthook.dll或texthost.dll，请重启游戏和翻译器后再试！ 的异常提示信息时，需要重启游戏和翻译器，这是因为强制退出时没有卸载干净hook导致的。

**Comment by hzl2010** [comment]
> 2.0版本在出现 无法复制texthook.dll或texthost.dll，请重启游戏和翻译器后再试！ 的异常提示信息时，需要重启游戏和翻译器，这是因为强制退出时没有卸载干净hook导致的。

没用。重启了也hook不了。一hook就报错。

**Comment by hzl2010** [comment]
> 2.0版本在出现 无法复制texthook.dll或texthost.dll，请重启游戏和翻译器后再试！ 的异常提示信息时，需要重启游戏和翻译器，这是因为强制退出时没有卸载干净hook导致的。

没用。重启了翻译器和游戏也hook不了。一hook就报错。

**Comment by hzl2010** [comment]
> 2.0版本在出现 无法复制texthook.dll或texthost.dll，请重启游戏和翻译器后再试！ 的异常提示信息时，需要重启游戏和翻译器，这是因为强制退出时没有卸载干净hook导致的。

只能重启电脑。

**Comment by hanmin0822** [comment]
2.2版本已经Release，尝试使用，出现bug的概率小很多

**Comment by imba-tjd** [comment]
现在的版本早就不使用此方式了，故关闭。
