### ISSUE TITLE
在游戏存档的位置，会导致翻译器闪退

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#32]
**关于哪一项功能**
闪退

**问题描述**
 hook成功后，点击部分游戏的存档或者读档，会导致翻译器闪退。

**应用版本**
V2.0

**系统信息**
win10 x64

**Comment by tpxxn** [comment]
可否提供游戏下载链接

**Comment by hzl2010** [comment]
> 可否提供游戏下载链接

姉姉Ｗ催眠
magnet:?xt=urn:btih:C1014DD2FF78379A84F9B03BA16D72DEBDFD9EA8
有别的游戏也是这样。

**Comment by hanmin0822** [comment]
2.1版本已添加字数翻译长度限制，速度限制等还在制作，目前提供了暂停/恢复功能用于存档和快进游戏时使用。
