### ISSUE TITLE
翻译框显示问题

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#33]
**关于哪一项功能**
翻译框显示问题
**期望的效果**
翻译框文字间行间距太大，而且会出现显示不全的情况。每次都得手动调整。
还不如1.5版的翻译框好。。。

**Comment by HumphreyDotSln** [comment]
我懂
我早想好咋改了
等我摸完鱼就改

**Comment by HumphreyDotSln** [comment]
解决了
