### ISSUE TITLE
hook游戏添加识别方法后，御坂翻译机崩溃

### ISSUE THREAD

**Issue by kuzuda** [hanmin0822/MisakaTranslator#332]
**关于哪一项功能**
hook游戏添加识别方法后，御坂翻译机崩溃

**问题描述**

hook模式识别文字，对游戏添加识别方式后，设置窗口消失后崩溃

**应用版本**

2.12.2.0

**系统信息**

win10 x64

**错误信息**

==============System Info================
System:Microsoft Windows NT 10.0.19045.0
CurrentTime:2024-03-27 0:13
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.12.2.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionName:System.Exception
ExceptionSource:TranslatorLibrary
ExceptionMessage:Patch File is not Exists.
ExceptionStackTrace:   在 TranslatorLibrary.ArtificialTranslator.TranslatorInit(String patchPath, String param2) 位置 D:\a\MisakaTranslator\MisakaTranslator\TranslatorLibrary\ArtificialTranslator.cs:行号 92
   在 MisakaTranslator_WPF.TranslateWindow.TranslatorAuto(String translator) 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\TranslateWindow.xaml.cs:行号 266
   在 MisakaTranslator_WPF.TranslateWindow..ctor() 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\TranslateWindow.xaml.cs:行号 107
   在 MisakaTranslator_WPF.MainWindow.<StartTranslateByGid>d__22.MoveNext() 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\MainWindow.xaml.cs:行号 271
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 MisakaTranslator_WPF.MainWindow.<StartBtn_Click>d__24.MoveNext() 位置 D:\a\MisakaTranslator\MisakaTranslator\MisakaTranslator-WPF\MainWindow.xaml.cs:行号 285
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by imba-tjd** [comment]
https://github.com/hanmin0822/MisakaTranslator/issues/193
https://github.com/hanmin0822/MisakaTranslator/issues/215
