### ISSUE TITLE
各种操作都会出现全局无法解析的错误

### ISSUE THREAD

**Issue by liuqy123** [hanmin0822/MisakaTranslator#35]
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/5/29 18:19
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.1.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionSource:TextHookLibrary
ExceptionMessage:试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)
ExceptionStackTrace:   在 TextHookLibrary.TextHostLib.DetachProcess(UInt32 processId)
   在 TextHookLibrary.TextHookHandle.Finalize()

2.0都没事

**Comment by hanmin0822** [comment]
2.2版本已经Release，尝试使用，出现bug的概率小很多
