### ISSUE TITLE
关于共享辞书实现方式的建议

### ISSUE THREAD

**Issue by bookyue** [hanmin0822/MisakaTranslator#37]
**共享辞书实现方式**
在知乎看到了作者在评论区提到目前还在思考没有服务器怎么实现共享辞书的问题
不知道作者这段时间有没有想到什么好的方法
如果还没有，我有一个小小的建议，可以考虑使用[IPFS(InterPlanetary File System)](https://ipfs.io/)来实现。
**期望的效果**
不使用服务器实现共享辞书

**Comment by hanmin0822** [comment]
分布式文件系统我一开始就有思考过，其实现在并不是实现功能的问题，而是人手不够的问题，之前一段时间我有空闲的时间，最近开始比较忙了，这个软件的制作进度也只能慢慢推进了，不过还是感谢你的建议！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bookyue"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月30日(星期六) 上午10:31
收件人:&nbsp;"hanmin0822/MisakaTranslator"<MisakaTranslator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[hanmin0822/MisakaTranslator] 关于共享辞书实现方式的建议 (#37)





 
共享辞书实现方式
 在知乎看到了作者在评论区提到目前还在思考没有服务器怎么实现共享辞书的问题
 不知道作者这段时间有没有想到什么好的方法
 如果还没有，我有一个小小的建议，可以考虑使用IPFS(InterPlanetary File System)来实现。
 期望的效果
 不使用服务器实现共享辞书

**Comment by HumphreyDotSln** [comment]
首先感谢您的建议，但是国内的网络环境对基于P2P的系统不友好，所以IPFS来实现共享辞书是不现实的。
事实上我们并不缺少储存方案，比如通过一些Serverless服务绕过GFW访问Firebase就可以实现，共享辞书的主要难点在于社区建设不成熟。
我们将优先提升软件的可用性，共享辞书将会在一个用户友好的版本推出之后面世

**Comment by bookyue** [comment]
原来如此，倒是我想当然了
不管怎样，感谢你们现在的工作！
