### ISSUE TITLE
v2.0翻译过程中闪退

### ISSUE THREAD

**Issue by RedContritio** [hanmin0822/MisakaTranslator#38]
**问题描述**

翻译过程中闪退

**应用版本**

V2.0 x86

**系统信息**

Windows10 x64

**错误信息**

==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/5/30 11:22
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.0.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionSource:Newtonsoft.Json
ExceptionMessage:Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
ExceptionStackTrace:   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.JsonTextReader.Read()
   在 Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 TranslatorLibrary.YoudaoTranslator.Translate(String sourceText, String desLang, String srcLang)
   在 MisakaTranslator_WPF.TranslateWindow.<>c__DisplayClass22_0.<DataRecvEventHandler>b__0()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by hanmin0822** [comment]
这是有道的bug导致的，请尝试不是用有道翻译API再试，如果出现错误再继续反馈。
另外2.2版本已经Release，尝试使用，出现bug的概率小很多

**Comment by imba-tjd** [comment]
#82
