### ISSUE TITLE
无脑报错 全局无法解决的异常

### ISSUE THREAD

**Issue by yurichoco** [hanmin0822/MisakaTranslator#40]
[
**问题描述**

**应用版本**

V2.0

**系统信息**

windows10 x64
**错误信息**

]([url](url))

![QQ截图20200530142610](https://user-images.githubusercontent.com/62846168/83320348-87bcce00-a281-11ea-9d29-ba21879c2568.png)
[2020-05-30 14-21-02.txt](https://github.com/hanmin0822/MisakaTranslator/files/4705129/2020-05-30.14-21-02.txt)

**附加截图**

**Comment by hanmin0822** [comment]
2.2版本已经Release，尝试使用，出现bug的概率小很多
