### ISSUE TITLE
老是出现全局无法解决的异常（点确定后程序会出现停止工作）

### ISSUE THREAD

**Issue by Yang7749a** [hanmin0822/MisakaTranslator#41]
**关于哪一项功能**

**问题描述**

**应用版本**

**系统信息**

**错误信息**

**附加截图**

**Comment by HumphreyDotSln** [comment]
需要更多细节

**Comment by Yang7749a** [comment]
[2020-05-30 19-55-29.txt](https://github.com/hanmin0822/MisakaTranslator/files/4705571/2020-05-30.19-55-29.txt)
[2020-05-30 19-55-26.txt](https://github.com/hanmin0822/MisakaTranslator/files/4705574/2020-05-30.19-55-26.txt)

**Comment by Yang7749a** [comment]
![image](https://user-images.githubusercontent.com/57832596/83327676-409a0180-a2b0-11ea-9204-2d24a43e88ce.png)
按照他说的选64版本注入就会崩溃 有的时候用全局ocr也会崩溃

**Comment by Yang7749a** [comment]
用le转区启动也会出现程序崩溃

**Comment by HumphreyDotSln** [comment]
2.x版本暂不完善，可以到官网下载1.5版本。

**Comment by Yang7749a** [comment]
版本用的2.1

**Comment by Yang7749a** [comment]
嗯  我试试

**Comment by Yang7749a** [comment]
1.5是不是不能加特殊码呀 up

**Comment by hanmin0822** [comment]
2.2版本已经Release，尝试使用，出现bug的概率小很多
