### ISSUE TITLE
错误bug

### ISSUE THREAD

**Issue by StarWC** [hanmin0822/MisakaTranslator#43]
[logs.zip](https://github.com/hanmin0822/MisakaTranslator/files/4748264/logs.zip)

崩溃属实有点频繁，整合成压缩包上传给您

**Comment by HumphreyDotSln** [comment]
请尝试最新的2.2版本

**Comment by StarWC** [comment]
这边还没看到新的发布，晚些看到了再试试吧ヾ(๑╹◡╹)ﾉ"
