### ISSUE TITLE
去重功能建议

### ISSUE THREAD

**Issue by hzl2010** [hanmin0822/MisakaTranslator#45]
**关于哪一项功能**
去重功能。
现在有很多重复的情况是无法去重的。
例如：a，ab，abc，abcd，abcde。这种文本
还有就是：abcde abcde abcde abcde。这种文本
**期望的效果**
最好能做到像vnr一样能去除这两种重复的文本。
还有就是除了常用的标点符号外，其它乱七八糟夹在文本里的标点符号，最好也能去除。

**Comment by hzl2010** [comment]
> **关于哪一项功能**
> 去重功能。
> 现在有很多重复的情况是无法去重的。
> 例如：a，ab，abc，abcd，abcde。这种文本
> 还有就是：abcde abcde abcde abcde。这种文本
> **期望的效果**
> 最好能做到像vnr一样能去除这两种重复的文本。
> 还有就是除了常用的标点符号外，其它乱七八糟夹在文本里的标点符号，最好也能去除。

不会编程的用户自己写这个有点麻烦。。

**Comment by HumphreyDotSln** [comment]
你说的这两种重复
1.5版本都可以去重了
2.0当然可以
还有就是一些符号就只能写正则匹配掉
下个版本会支持在其他去重方式的基础上匹配正则
