### ISSUE TITLE
Misaka translator发现了全局无法解决的异常，即将强制退出。

### ISSUE THREAD

**Issue by Cath412** [hanmin0822/MisakaTranslator#50]
**关于哪一项功能**
程序正常使用时崩溃

**问题描述**
使用hook，正常翻译过程中，突然只有原文出现，本该是翻译文本的地方显示“等待原文本，点击“重新翻译”，蹦出提示“出现全局无法解决的问题”，然后程序自动退出。重启程序，找到合适的hook方法后接着出现上述问题，已然无法正常翻译

**应用版本**
V2.2

**系统信息**
 例如Windows10 x64

**错误信息**
错误提示：Misaka translator发现了全局无法解决的异常，即将强制退出。关于本次异常的详细信息已经存储在logs目录下的2020-06-18 14-29-02文件中，为了更好地维护本软件，我们希望您能将此文件发送给作者以修复这个问题。

logs文件内容：
> ==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/6/18 10:47
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.2.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionSource:Newtonsoft.Json
ExceptionMessage:Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
ExceptionStackTrace:   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.JsonTextReader.Read()
   在 Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 TranslatorLibrary.YoudaoTranslator.Translate(String sourceText, String desLang, String srcLang)
   在 MisakaTranslator_WPF.TranslateWindow.<>c__DisplayClass24_0.<DataRecvEventHandler>b__0()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**附加截图**
![C~I4G)0F24M5K%~(~SOYZ1O](https://user-images.githubusercontent.com/67086938/84986380-0fa34300-b171-11ea-8e88-1b4d792fb29b.png)

**Comment by hanmin0822** [comment]
这是json解析的错误，请不要使用有道翻译

**Comment by Cath412** [comment]
> 这是json解析的错误，请不要使用有道翻译

谢谢！去掉有道翻译后可以正常使用了
