### ISSUE TITLE
国外玩家无法申请百度API

### ISSUE THREAD

**Issue by jiaxiang11144** [hanmin0822/MisakaTranslator#51]
**关于哪一项功能**API和辞典问题
百度API不让马来西亚申请，还有请问辞典方面能用自己下载的吗，怎么设置，因为小学馆的日语真的太少，根本翻译不了我的游戏

**期望的效果**

**Comment by jiaxiang11144** [comment]
> **关于哪一项功能**API和辞典问题
> 
> 百度API不让马来西亚申请，还有请问辞典方面能用自己下载的吗，怎么设置，因为小学馆的日语真的太少，根本翻译不了我的游戏
> **期望的效果**

能借我一个账号或其他的方法

**Comment by hanmin0822** [comment]
目前的解决办法是使用本软件提供的三种离线翻译API，后续软件将提供谷歌或DEEPL等翻译API供国外用户使用

**Comment by hanmin0822** [comment]
2.3版本已支持谷歌翻译，如果人在国外无法访问谷歌CN的，可以将代码中后缀.cn改为.com后再编译使用
