### ISSUE TITLE
有时候点语音或者历史文本会闪退

### ISSUE THREAD

**Issue by zt7749** [hanmin0822/MisakaTranslator#57]
[](url)
[logs.zip](https://github.com/hanmin0822/MisakaTranslator/files/4822894/logs.zip)
拜托修复一下

**Comment by hanmin0822** [comment]
并非语言和历史文本功能问题，属于名词优化系统的bug，请先不要使用指定名词翻译等功能，将目录下的TransOptimization文件夹删除即可。

**Comment by zt7749** [comment]
原来是指定翻译出错啦，我试试哦谢大佬

QiHanmin <notifications@github.com> 于2020年6月24日周三 上午10:29写道：
