### ISSUE TITLE
请问dll方式调用texthook与使用cli有什么不同吗？

### ISSUE THREAD

**Issue by luojunyuan** [hanmin0822/MisakaTranslator#58]
我看到commit中有一条，“放弃使用DLL形式的Texthook方式，继续使用之前的控制台读取形式并做出优化”

**Comment by hanmin0822** [comment]
DLL形式的Hook方式见https://github.com/lgztx96/texthost
由于用户不太会使用导致频繁出错，违反了本翻译器简单易用的初衷，故还是改回之前的控制台读取形式
