### ISSUE TITLE
闪退且没有记录日志，希望追加普通日志

### ISSUE THREAD

**Issue by lxflxf56** [hanmin0822/MisakaTranslator#64]
**关于哪一项功能**
日志功能

**问题描述**

在正常运行的情况下，突然窗口没有了，去查日志也发现没有任何日志，望追加普通日志输出，或者在最上层捕获下异常

**应用版本**

2.4 rel

**系统信息**

Windows10 x64 

**错误信息**

**附加截图**

**Comment by hanmin0822** [comment]
全部捕获异常是已经实现了的，请描述一下软件整个崩溃之前的操作

**Comment by lxflxf56** [comment]
并没有做什么特别的操作，目前是hook上游戏，选择特殊码后，在游戏里点下一句，点了两三句就会出现软件崩溃，整个进程都不见了，不是卡住或者弹窗说错误，我在另外个游戏上不会出现这种情况
