### ISSUE TITLE
希望能增加文本去重功能

### ISSUE THREAD

**Issue by lxflxf56** [hanmin0822/MisakaTranslator#65]
**关于哪一项功能**

希望能增加文本去重功能，类似于vnr
*期望的效果**
文本如下
睦姫「ふぇ！？　えっと……その」「ふぇ！？　えっと……その」
去重后变成
睦姫「ふぇ！？　えっと……その」

**Comment by hanmin0822** [comment]
句子去重功能已经实现，基本算法思想是倒找文本，找到第一个匹配的字符后返回后面的文本。
如果您能提供更好的算法思想也可描述出来或直接提供代码（任意语言皆可）

**Comment by lxflxf56** [comment]
我的想法是
有以下重复的语句 
String s="AB_CDE_CDE"
//取最后个字符 a='E' 
与之它前面的字符长度做比较
即 'D' == 'E'?
然后继续
'_C'=='DE'?
往前推 循环下去
'DE_'=='CDE'?
'_CDE'=='_CDE'匹配成功，去重
建议可以设置去重最低长度，最低3个字符匹配成功才进行去重

这种算法是可以复合我遇到的场景，但估计还可能会有其他场景，作者可以多考虑下

**Comment by hanmin0822** [comment]
软件中目前使用的算法就是这种，且支持自定义匹配字符的个数，使用句子去重，将阈值设为3即可。
