### ISSUE TITLE
MisakaHookFinder能找到的Hook MisakaTranslator找不到只有一条

### ISSUE THREAD

**Issue by LingyueS** [hanmin0822/MisakaTranslator#67]
**关于哪一项功能**
MisakaHookFinder能找到的Hook MisakaTranslator找不到只有一条
Secret Agent～騎士学園の忍びなるもの～
35:38BC:4C0720:466EED:0:UserHook2:HQC@C0720:AdvHD.exe
这个是正确的
但MisakaTranslator只有一条错的没有其他

**问题描述**

**应用版本**

2.5

**系统信息**

Windows10 x64

**错误信息**

**附加截图**

**Comment by hanmin0822** [comment]
看了一下hook特殊码，你这个是使用MisakaHookFinder的特殊码搜索功能查到的，本来MisakaHookFinder和MisakaTranslator的作用范围就不同，MisakaHookFinder就是用来查找MisakaTranslator找不到的特殊码，使用MisakaHookFinder查找到的特殊码经过处理（如题为/HQC@C0720:AdvHD.exe）填写进MisakaTranslator即可或者直接使用剪贴板读取。
