### ISSUE TITLE
疑似百度翻译崩溃Bug

### ISSUE THREAD

**Issue by ETWXR9** [hanmin0822/MisakaTranslator#72]
**关于哪一项功能**
在线翻译

**问题描述**

在翻译RM游戏之类因战斗系统等原因频繁刷新文字的情况下，使用百度翻译时翻译器容易崩溃，且没有崩溃提示和记录崩溃日志。
作为对照，在同样的两个游戏（引擎分别为RMMV RMXP）上单独使用J北京本地翻译，以及腾讯翻译，都没有出现崩溃情况。

**应用版本**

2.5

**系统信息**

Windows10 x64 专业版 1903 18362.900

**错误信息**

无任何弹窗提示，程序直接消失。没有Log。

**附加截图**

**Comment by hanmin0822** [comment]
应该做翻译间隔时间限制，作为待开发功能记录

**Comment by imba-tjd** [comment]
理论上现在不会出现了
