### ISSUE TITLE
对于英文游戏，翻译一段时间后即崩溃

### ISSUE THREAD

**Issue by yanjunqi** [hanmin0822/MisakaTranslator#76]
**关于哪一项功能**

**问题描述**

对于英文游戏，翻译一段时间后即崩溃

**应用版本**

V2.6

**系统信息**

Windows10 x64专业版

**错误信息**

==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:20/7/16 10:28
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.6.0.0
==============Exception Info================
ExceptionType:Non UI Thread
ExceptionSource:ArtificialTransHelperLibrary
ExceptionMessage:未将对象引用设置到对象的实例。
ExceptionStackTrace:   在 ArtificialTransHelperLibrary.ArtificialTransHelper.AddTrans(String source, String Trans)
   在 MisakaTranslator_WPF.TranslateWindow.<>c__DisplayClass28_0.<DataRecvEventHandler>b__0()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 System.Windows.Application.Run(Window window)
   在 MisakaTranslator_WPF.App.Main()

**附加截图**

**Comment by imba-tjd** [comment]
你试试我构建的开发版有没有问题
https://github.com/imba-tjd/MisakaTranslator/suites/922483387/artifacts/11270801

**Comment by Jmayy** [comment]
> 你试试我构建的开发版有没有问题
> https://github.com/imba-tjd/MisakaTranslator/suites/922483387/artifacts/11270801
同样的错误

**Comment by imba-tjd** [comment]
emmmmm那我是不会修:joy:等Owner看吧

**Comment by hanmin0822** [comment]
首先检查英文游戏的游戏限制字数，如果限制字数过少导致源文本为空时会出现此错误。
如果还存在问题，在设置中关闭人工翻译记录选项
