### ISSUE TITLE
强制退出Bug

### ISSUE THREAD

**Issue by 37395268** [hanmin0822/MisakaTranslator#80]
**关于哪一项功能**
程序强制退出

**问题描述**
点击{完成设置} 出现弹窗内容如下：
MisakaTranslator发现全局无法解决异常，即将强制退出。关于本次异常的详细信息已经存储在logs目录下的2020-07-21 12-42-30 文件中，为了更好地维护本软件，我们希望您能将此文件发送给作者解决此问题。

**应用版本**
RPG正義の変身ヒロインを支える俺と悪の女幹部【日语】  1.0.0.0

**系统信息**
Windows10 家庭版 1909

**错误信息**
==============System Info================
System:Microsoft Windows NT 6.2.9200.0
CurrentTime:2020/7/21 12:42
dotNetVersion:4.0.30319.42000
MisakaTranslatorVersion:2.7.0.0
==============Exception Info================
ExceptionType:UI Thread
ExceptionSource:TranslatorLibrary
ExceptionMessage:Patch File is not Exists.
ExceptionStackTrace:   在 TranslatorLibrary.ArtificialTranslator.TranslatorInit(String patchPath, String param2)
   在 MisakaTranslator_WPF.TranslateWindow.TranslatorAuto(String translator)
   在 MisakaTranslator_WPF.TranslateWindow..ctor()
   在 MisakaTranslator_WPF.GameGuideWindow.Next_Click(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 MisakaTranslator_WPF.GuidePages.CompletationPage.ConfirmBtn_Click(Object sender, RoutedEventArgs e)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

ps：没有用去重， 杀毒软件已关，用管理员开启程序

**Comment by 37395268** [comment]
使用MisakaTranslator2.7

**Comment by hanmin0822** [comment]
不是bug，你这个情况是用了人工翻译但没有设置文件路径。
详见：https://www.bilibili.com/video/BV1wC4y1h7yC/

**Comment by 37395268** [comment]
但我没开该功能也出现同样问题

**Comment by hanmin0822** [comment]
1.所有崩溃bug显示都是这个信息框，但是错误不同，以错误文件显示为准。
2.你说的没开这个这个功能是指没开启人工翻译记录，还是把第一第二翻译源都换成 非 人工翻译选项？请仔细区分，教程视频中强调的内容不再解答

**Comment by 37395268** [comment]
没开人工翻译记录以及第一第二翻译都换成 非 人工翻译选项  也有该问题出现

**Comment by hanmin0822** [comment]
确认问题本质，如果你确定是跟这个相同的问题，直接联系我QQ，备注github问题编号

**Comment by 37395268** [comment]
解决了，重新开一次电脑，再重新过流程就不知道怎么的就解决了。
