### ISSUE TITLE
自动开始翻译以前配置过的游戏这个功能不起作用

### ISSUE THREAD

**Issue by asd8299128** [hanmin0822/MisakaTranslator#88]
**关于哪一项功能**
自动关联正在运行的、之前已经完成配置的游戏

**问题描述**
点击那个火箭之后提示“未在当前进程列表中找到可以自动开始翻译的游戏”

**应用版本**
V2.7

**系统信息**
Windows7 x64

**错误信息**
虽然这句话可能不该说，但大佬不会是只记录PID和特殊码吧？这样根本无法关联撒，至少把程序.exe的名称和游戏根目录路径记住吧……

**Comment by hanmin0822** [comment]
当然不可能记录PID，记录的就是所选择游戏的本地实际路径，但是由于某些游戏是多进程的或者后缀名不是exe文件，这时候就出现无法关联的情况。游戏库的详细记录信息以sqlite文件形式存储在软件根目录下
