### ISSUE TITLE
Are there any free translator and ocr?

### ISSUE THREAD

**Issue by toprak** [hanmin0822/MisakaTranslator#90]
Hi, I do not know how to use it, I just want to read manga as translated. But I could not find free translator and free ocr. 
Thanks in advance.

**Comment by hanmin0822** [comment]
If you are outside the Chinese mainland, you are advised to use Google translator (or try to register other online translator) and Tesseract OCR. Baidu OCR should also be able to register to use. They are all free.

**Comment by toprak** [comment]
I have registered to baidu, but I guess it is paid?

**Comment by hanmin0822** [comment]
The API provided on MisakaTranslator has a large amount of free quota. You need to go to the official website of each API for the corresponding instructions.

**Comment by toprak** [comment]
The problem is there are no api key provided on MisakaTranslator. 
![Capture](https://user-images.githubusercontent.com/43301560/89304377-09f8b280-d676-11ea-849d-2a68b1f7e11c.PNG)
Other options are same.

**Comment by hanmin0822** [comment]
Of course, you need to apply for these apikeys on the corresponding official website by yourself. Some ways to apply for the API may be found on YouTube in English. If you can program yourself, you can modify the Translator class library of this project to make your own translator.
