### ISSUE TITLE
翻譯框無法移動

### ISSUE THREAD

**Issue by efklf3k3i3** [hanmin0822/MisakaTranslator#91]
**关于哪一项功能**
翻譯框無法移動

**问题描述**

hook遊戲之後，跑出的翻譯框是固定的，可以改變大小尺寸，但無法拖拉移動

**应用版本**

2.7

2.5可以

**系统信息**

Windows10 x64 2004

**错误信息**

**附加截图**

**Comment by hanmin0822** [comment]
翻译框界面的左上角 第二个图标 按住即可拖动

**Comment by efklf3k3i3** [comment]
> 翻译框界面的左上角 第二个图标 按住即可拖动

解決了
可能是縮放時遮到了圖標沒發現
感謝~
