### ISSUE TITLE
抓3d中的文字hook时极慢，抓到以后任然0.1fps等同于无法使用，过滤graphics的loop或者每隔一段时间检查memory？

### ISSUE THREAD

**Issue by Fireflaker** [hanmin0822/MisakaTranslator#95]
抓3d中的文字hook时1分钟一帧，至少要花5分钟抓到
抓到以后运行游戏一般已经卡死了
配置：8核3.8Ghz, 1070Ti, Nvme SSD.

抓取时CPU占用99%

**期望的效果**

过滤graphics的loop或者每隔一段时间检查memory？
使得3d游戏可用。

**Comment by Fireflaker** [comment]
不确定是否是因为游戏有anti debugger。游戏似乎用的是unity的3d

**Comment by hanmin0822** [comment]
尝试打开设置中的删除无用hook选项或者使用特定的unity游戏文字提取工具，然后使用剪贴板监控方式翻译
