### ISSUE TITLE
快速复制当前语句

### ISSUE THREAD

**Issue by huanlingzx** [hanmin0822/MisakaTranslator#96]
想要复制语句在其他翻译软件翻译，或其它工具中进行分析。

现在好像是只能点开历史记录，然后手动复制，稍微有点麻烦。

希望抓取到语句后可以自动复制当前语句，或者提供一个按钮点一下就可以复制当前语句。

**Comment by hanmin0822** [comment]
使用hookfinder来实现你要求的效果https://github.com/hanmin0822/MisakaHookFinder
