### ISSUE TITLE
翻译界面设置中中将原文字体大小调制0会导致崩溃

### ISSUE THREAD

**Issue by qingqhua** [hanmin0822/MisakaTranslator#98]
**关于哪一项功能**
在翻译界面中将原文大小调制0会导致崩溃

**问题描述**

在翻译界面上进行设置, 不将原文隐藏,将原文字体大小调整至0

**应用版本**

v2.7

**系统信息**

windows10 x64

**错误信息**

弹出全局设置错误的窗口

**附加截图**

**Comment by imba-tjd** [comment]
fixed in 5959c7231a80473c27728ceb4ccd3b0200f0e751
