### ISSUE TITLE
翻译界面ui显示不正确

### ISSUE THREAD

**Issue by qingqhua** [hanmin0822/MisakaTranslator#99]
**关于哪一项功能**
翻译界面ui显示, 拖曳窗口按钮

**问题描述**

在翻译界面将翻译窗口大小调整到很小, 拖曳窗口的ui按钮会消失. eg. 将翻译界面的宽度缩小

**应用版本**

v2.7

**系统信息**

windows10 x64

**错误信息**

没有弹出错误

**附加截图**

**Comment by AndromedaMelody** [comment]
Fix in c212c199cf1e200dbf167dd409b6f137c9fd85be 2c04ce31d0d590a3571669ed9885bed51f1cddc5
